create table ref_weather_forecast_16day
(
	outcode varchar(16383),
	city_name varchar(16383),
	lon varchar(16383),
	timezone varchar(16383),
	lat varchar(16383),
	country_code varchar(16383),
	state_code varchar(16383),
	moonrise_ts bigint encode az64,
	wind_cdir varchar(16383),
	rh bigint encode az64,
	pres double precision,
	high_temp double precision,
	sunset_ts bigint encode az64,
	ozone double precision,
	moon_phase double precision,
	wind_gust_spd double precision,
	snow_depth double precision,
	clouds bigint encode az64,
	ts bigint encode az64,
	sunrise_ts bigint encode az64,
	app_min_temp double precision,
	wind_spd double precision,
	pop bigint encode az64,
	wind_cdir_full varchar(16383),
	slp double precision,
	moon_phase_lunation double precision,
	valid_date varchar(16383),
	app_max_temp double precision,
	vis double precision,
	dewpt double precision,
	snow double precision,
	uv double precision,
	wind_dir bigint encode az64,
	max_dhi varchar(16383),
	clouds_hi bigint encode az64,
	precip double precision,
	low_temp double precision,
	max_temp double precision,
	moonset_ts bigint encode az64,
	datetime varchar(16383),
	temp double precision,
	min_temp double precision,
	clouds_mid bigint encode az64,
	clouds_low bigint encode az64,
	etlchange timestamp encode az64
)
;

alter table ref_weather_forecast_16day owner to igloo
;

create table ref_weather_forecast_hourly
(
	outcode varchar(256),
	city_name varchar(256),
	lon varchar(256),
	timezone varchar(256),
	lat varchar(256),
	country_code varchar(256),
	state_code varchar(256),
	forecast_issued varchar(256),
	wind_cdir varchar(256),
	rh bigint encode az64,
	pod varchar(256),
	timestamp_utc varchar(256),
	pres real,
	solar_rad real,
	ozone real,
	icon varchar(256),
	code bigint encode az64,
	description varchar(256),
	wind_gust_spd real,
	timestamp_local varchar(256),
	snow_depth real,
	clouds bigint encode az64,
	ts bigint encode az64,
	wind_spd real,
	pop bigint encode az64,
	wind_cdir_full varchar(256),
	slp real,
	dni real,
	dewpt real,
	snow real,
	uv real,
	wind_dir bigint encode az64,
	clouds_hi bigint encode az64,
	precip real,
	vis real,
	dhi real,
	app_temp real,
	datetime varchar(256),
	temp real,
	ghi real,
	clouds_mid bigint encode az64,
	clouds_low bigint encode az64,
	etlchange timestamp encode az64
)
;

alter table ref_weather_forecast_hourly owner to igloo
;

create table ref_weather_forecast_daily
(
	outcode varchar(256),
	city_name varchar(256),
	lon varchar(256),
	timezone varchar(256),
	lat varchar(256),
	country_code varchar(256),
	state_code varchar(256),
	moonrise_ts bigint encode az64,
	wind_cdir varchar(256),
	rh bigint encode az64,
	pres real,
	high_temp real,
	sunset_ts bigint encode az64,
	ozone real,
	moon_phase real,
	wind_gust_spd real,
	snow_depth real,
	clouds bigint encode az64,
	ts bigint encode az64,
	sunrise_ts bigint encode az64,
	app_min_temp real,
	wind_spd real,
	pop bigint encode az64,
	wind_cdir_full varchar(256),
	slp real,
	moon_phase_lunation real,
	valid_date varchar(256),
	app_max_temp real,
	vis real,
	dewpt real,
	snow real,
	uv real,
	wind_dir bigint encode az64,
	max_dhi varchar(256),
	clouds_hi bigint encode az64,
	precip real,
	low_temp real,
	max_temp real,
	moonset_ts bigint encode az64,
	datetime varchar(256),
	temp real,
	min_temp real,
	clouds_mid bigint encode az64,
	clouds_low bigint encode az64,
	etlchange timestamp encode az64
)
;

alter table ref_weather_forecast_daily owner to igloo
;

