create table ref_epc_certificates_all
(
	lmk_key varchar(500),
	address1 varchar(1000),
	address2 varchar(1000),
	address3 varchar(1000),
	postcode varchar(255) distkey,
	building_reference_number bigint,
	current_energy_rating varchar(10) encode bytedict,
	potential_energy_rating varchar(10) encode bytedict,
	current_energy_efficiency bigint encode delta,
	potential_energy_efficiency bigint encode delta,
	property_type varchar(255),
	built_form varchar(255),
	inspection_date varchar(255),
	local_authority varchar(255),
	constituency varchar(255),
	county varchar(255),
	lodgement_date varchar(255),
	transaction_type varchar(255),
	environment_impact_current bigint encode delta,
	environment_impact_potential bigint encode delta,
	energy_consumption_current double precision encode bytedict,
	energy_consumption_potential double precision encode bytedict,
	co2_emissions_current double precision encode bytedict,
	co2_emiss_curr_per_floor_area double precision encode bytedict,
	co2_emissions_potential double precision encode bytedict,
	lighting_cost_current double precision encode bytedict,
	lighting_cost_potential double precision encode bytedict,
	heating_cost_current double precision,
	heating_cost_potential double precision encode bytedict,
	hot_water_cost_current double precision encode bytedict,
	hot_water_cost_potential double precision encode bytedict,
	total_floor_area double precision encode bytedict,
	energy_tariff varchar(255),
	mains_gas_flag varchar(10),
	floor_level varchar(255),
	flat_top_storey varchar(10),
	flat_storey_count bigint,
	main_heating_controls varchar(255),
	multi_glaze_proportion bigint,
	glazed_type varchar(255),
	glazed_area varchar(255),
	extension_count bigint,
	number_habitable_rooms bigint encode delta,
	number_heated_rooms bigint encode delta,
	low_energy_lighting bigint encode delta,
	number_open_fireplaces bigint,
	hotwater_description varchar(255),
	hot_water_energy_eff varchar(255),
	hot_water_env_eff varchar(255),
	floor_description varchar(255),
	floor_energy_eff varchar(255),
	floor_env_eff varchar(255),
	windows_description varchar(255),
	windows_energy_eff varchar(255),
	windows_env_eff varchar(255),
	walls_description varchar(255),
	walls_energy_eff varchar(255),
	walls_env_eff varchar(255),
	secondheat_description varchar(255),
	sheating_energy_eff varchar(255),
	sheating_env_eff varchar(255),
	roof_description varchar(255),
	roof_energy_eff varchar(255),
	roof_env_eff varchar(255),
	mainheat_description varchar(255),
	mainheat_energy_eff varchar(255),
	mainheat_env_eff varchar(255),
	mainheatcont_description varchar(255),
	mainheatc_energy_eff varchar(255),
	mainheatc_env_eff varchar(255),
	lighting_description varchar(255),
	lighting_energy_eff varchar(255),
	lighting_env_eff varchar(255),
	main_fuel varchar(255),
	wind_turbine_count bigint,
	heat_loss_corridoor varchar(255),
	unheated_corridor_length double precision encode bytedict,
	floor_height double precision encode bytedict,
	photo_supply bigint,
	solar_water_heating_flag varchar(255),
	mechanical_ventilation varchar(255),
	address varchar(255),
	local_authority_label varchar(255),
	constituency_label varchar(255)
)
diststyle key
sortkey(postcode)
;

alter table ref_epc_certificates_all owner to igloo
;

create table ref_epc_certificates_igloo
(
	lmk_key varchar(500),
	address1 varchar(1000),
	address2 varchar(1000),
	address3 varchar(1000),
	postcode varchar(255) distkey,
	building_reference_number bigint,
	current_energy_rating varchar(10) encode bytedict,
	potential_energy_rating varchar(10) encode bytedict,
	current_energy_efficiency bigint encode delta,
	potential_energy_efficiency bigint encode delta,
	property_type varchar(255),
	built_form varchar(255),
	inspection_date varchar(255),
	local_authority varchar(255),
	constituency varchar(255),
	county varchar(255),
	lodgement_date varchar(255),
	transaction_type varchar(255),
	environment_impact_current bigint encode delta,
	environment_impact_potential bigint encode delta,
	energy_consumption_current double precision encode bytedict,
	energy_consumption_potential double precision encode bytedict,
	co2_emissions_current double precision encode bytedict,
	co2_emiss_curr_per_floor_area double precision encode bytedict,
	co2_emissions_potential double precision encode bytedict,
	lighting_cost_current double precision encode bytedict,
	lighting_cost_potential double precision encode bytedict,
	heating_cost_current double precision,
	heating_cost_potential double precision encode bytedict,
	hot_water_cost_current double precision encode bytedict,
	hot_water_cost_potential double precision encode bytedict,
	total_floor_area double precision encode bytedict,
	energy_tariff varchar(255),
	mains_gas_flag varchar(10),
	floor_level varchar(255),
	flat_top_storey varchar(10),
	flat_storey_count bigint,
	main_heating_controls varchar(255),
	multi_glaze_proportion bigint,
	glazed_type varchar(255),
	glazed_area varchar(255),
	extension_count bigint,
	number_habitable_rooms bigint encode delta,
	number_heated_rooms bigint encode delta,
	low_energy_lighting bigint encode delta,
	number_open_fireplaces bigint,
	hotwater_description varchar(255),
	hot_water_energy_eff varchar(255),
	hot_water_env_eff varchar(255),
	floor_description varchar(255),
	floor_energy_eff varchar(255),
	floor_env_eff varchar(255),
	windows_description varchar(255),
	windows_energy_eff varchar(255),
	windows_env_eff varchar(255),
	walls_description varchar(255),
	walls_energy_eff varchar(255),
	walls_env_eff varchar(255),
	secondheat_description varchar(255),
	sheating_energy_eff varchar(255),
	sheating_env_eff varchar(255),
	roof_description varchar(255),
	roof_energy_eff varchar(255),
	roof_env_eff varchar(255),
	mainheat_description varchar(255),
	mainheat_energy_eff varchar(255),
	mainheat_env_eff varchar(255),
	mainheatcont_description varchar(255),
	mainheatc_energy_eff varchar(255),
	mainheatc_env_eff varchar(255),
	lighting_description varchar(255),
	lighting_energy_eff varchar(255),
	lighting_env_eff varchar(255),
	main_fuel varchar(255),
	wind_turbine_count bigint,
	heat_loss_corridoor varchar(255),
	unheated_corridor_length double precision encode bytedict,
	floor_height double precision encode bytedict,
	photo_supply bigint,
	solar_water_heating_flag varchar(255),
	mechanical_ventilation varchar(255),
	address varchar(255),
	local_authority_label varchar(255),
	constituency_label varchar(255)
)
diststyle key
sortkey(postcode)
;

alter table ref_epc_certificates_igloo owner to igloo
;

