create table if not exists ref_readings_smart_readsinventory_audit
(
	    mpxn bigint distkey ,
      deviceid      Varchar(50),
      IHD_DeviceID      Varchar(50),
      IHD_DeviceStatus      Varchar(30),
      IHD_DeviceManufacturer      Varchar(20),
      IHD_DeviceModel      Varchar(20) ,
      IHD_SMETSCHTSVersion      Varchar(20),
      IHD_DeviceFirmwareVersion      Varchar(20)  ,
      IHD_DeviceFirmwareVersionStatus      Varchar(20)  ,
      IHD_CPLStatus      Varchar(20)  ,
      IHD_DateCommissioned      timestamp  ,
      IHD_ImportMPxN      bigint  ,
      IHD_SecondaryImportMPAN      bigint ,
      IHD_ExportMPAN      bigint  ,
      IHD_ESMEVariant      Varchar(20) ,
      IHD_UPRN      bigint ,
      GSME_DeviceID      Varchar(50) ,
      GSME_DeviceType      Varchar(20) ,
      GSME_DeviceStatus      Varchar(30) ,
      GSME_DeviceManufacturer      Varchar(20) ,
      GSME_DeviceModel      Varchar(20) ,
      GSME_SMETSCHTSVersion      Varchar(20) ,
      GSME_DeviceFirmwareVersion      Varchar(20) ,
      GSME_DeviceFirmwareVersionStatus      Varchar(20) ,
      GSME_CPLStatus      Varchar(20) ,
      GSME_DateCommissioned      timestamp ,
      GSME_ImportMPxN      bigint ,
      GSME_SecondaryImportMPAN      bigint ,
      GSME_ExportMPAN      bigint ,
      GSME_ESMEVariant      Varchar(20) ,
      GSME_UPRN      bigint ,
      ESME_DeviceID      Varchar(50) ,
      ESME_DeviceType      Varchar(20) ,
      ESME_DeviceStatus      Varchar(30) ,
      ESME_DeviceManufacturer      Varchar(20) ,
      ESME_DeviceModel      Varchar(20) ,
      ESME_SMETSCHTSVersion      Varchar(20) ,
      ESME_DeviceFirmwareVersion      Varchar(20) ,
      ESME_DeviceFirmwareVersionStatus      Varchar(20) ,
      ESME_CPLStatus      Varchar(20) ,
      ESME_ImportMPxN      bigint ,
      ESME_SecondaryImportMPAN      bigint ,
      ESME_ExportMPAN      bigint ,
      ESME_ESMEVariant      Varchar(20) ,
      ESME_UPRN      bigint ,
      GPF_DeviceID      Varchar(50) ,
      GPF_DeviceType      Varchar(20) ,
      GPF_DeviceStatus      Varchar(30) ,
      GPF_DeviceManufacturer      Varchar(20) ,
      GPF_DeviceModel      Varchar(20) ,
      GPF_SMETSCHTSVersion      Varchar(20) ,
      GPF_DeviceFirmwareVersion      Varchar(20) ,
      GPF_DeviceFirmwareVersionStatus      Varchar(20) ,
      GPF_CPLStatus      Varchar(20) ,
      GPF_ImportMPxN      bigint ,
      GPF_SecondaryImportMPAN      bigint ,
      GPF_ExportMPAN     bigint ,
      GPF_ESMEVariant      Varchar(20) ,
      GPF_UPRN      bigint,
    etlchangetype varchar(1),
    etlchange timestamp
)
diststyle key
sortkey(mpxn, deviceid)
;


alter table ref_readings_smart_readsinventory_audit owner to igloo
;



create table if not exists ref_readings_smart_readsinventory
(
	   mpxn bigint distkey ,
      deviceid      Varchar(50),
      IHD_DeviceID      Varchar(50),
      IHD_DeviceStatus      Varchar(30),
      IHD_DeviceManufacturer      Varchar(20),
      IHD_DeviceModel      Varchar(20) ,
      IHD_SMETSCHTSVersion      Varchar(20),
      IHD_DeviceFirmwareVersion      Varchar(20)  ,
      IHD_DeviceFirmwareVersionStatus      Varchar(20)  ,
      IHD_CPLStatus      Varchar(20)  ,
      IHD_DateCommissioned      timestamp  ,
      IHD_ImportMPxN      bigint  ,
      IHD_SecondaryImportMPAN      bigint ,
      IHD_ExportMPAN      bigint  ,
      IHD_ESMEVariant      Varchar(20) ,
      IHD_UPRN      bigint ,
      GSME_DeviceID      Varchar(50) ,
      GSME_DeviceType      Varchar(20) ,
      GSME_DeviceStatus      Varchar(30) ,
      GSME_DeviceManufacturer      Varchar(20) ,
      GSME_DeviceModel      Varchar(20) ,
      GSME_SMETSCHTSVersion      Varchar(20) ,
      GSME_DeviceFirmwareVersion      Varchar(20) ,
      GSME_DeviceFirmwareVersionStatus      Varchar(20) ,
      GSME_CPLStatus      Varchar(20) ,
      GSME_DateCommissioned      timestamp ,
      GSME_ImportMPxN      bigint ,
      GSME_SecondaryImportMPAN      bigint ,
      GSME_ExportMPAN      bigint ,
      GSME_ESMEVariant      Varchar(20) ,
      GSME_UPRN      bigint ,
      ESME_DeviceID      Varchar(50) ,
      ESME_DeviceType      Varchar(20) ,
      ESME_DeviceStatus      Varchar(30) ,
      ESME_DeviceManufacturer      Varchar(20) ,
      ESME_DeviceModel      Varchar(20) ,
      ESME_SMETSCHTSVersion      Varchar(20) ,
      ESME_DeviceFirmwareVersion      Varchar(20) ,
      ESME_DeviceFirmwareVersionStatus      Varchar(20) ,
      ESME_CPLStatus      Varchar(20) ,
      ESME_ImportMPxN      bigint ,
      ESME_SecondaryImportMPAN      bigint ,
      ESME_ExportMPAN      bigint ,
      ESME_ESMEVariant      Varchar(20) ,
      ESME_UPRN      bigint ,
      GPF_DeviceID      Varchar(50) ,
      GPF_DeviceType      Varchar(20) ,
      GPF_DeviceStatus      Varchar(30) ,
      GPF_DeviceManufacturer      Varchar(20) ,
      GPF_DeviceModel      Varchar(20) ,
      GPF_SMETSCHTSVersion      Varchar(20) ,
      GPF_DeviceFirmwareVersion      Varchar(20) ,
      GPF_DeviceFirmwareVersionStatus      Varchar(20) ,
      GPF_CPLStatus      Varchar(20) ,
      GPF_ImportMPxN      bigint ,
      GPF_SecondaryImportMPAN      bigint ,
      GPF_ExportMPAN     bigint ,
      GPF_ESMEVariant      Varchar(20) ,
      GPF_UPRN      bigint,
    etlchange timestamp
)
diststyle key
sortkey(mpxn, deviceid)
;


alter table ref_readings_smart_readsinventory owner to igloo
;