select count(*) from (SELECT dspinventory_cad_cplstatus,
       dspinventory_cad_cspregion,
       dspinventory_cad_datecommissioned,
       dspinventory_cad_devicefirmwareversion,
       dspinventory_cad_devicefirmwareversionstatus,
       dspinventory_cad_devicegbcsversion,
       dspinventory_cad_deviceid,
       dspinventory_cad_devicemanufacturer,
       dspinventory_cad_devicemodel,
       dspinventory_cad_devicestatus,
       dspinventory_cad_devicetype,
       dspinventory_cad_esmevariant,
       dspinventory_cad_exportmpan,
       dspinventory_cad_hanvariant,
       dspinventory_cad_importmpxn,
       dspinventory_cad_propertyfilter_addressidentifier,
       dspinventory_cad_propertyfilter_postcode,
       dspinventory_cad_s1sp,
       dspinventory_cad_smetschtsversion,
       dspinventory_cad_secondaryimportmpan,
       dspinventory_cad_uprn,
       dspinventory_chf_cplstatus,
       dspinventory_chf_cspregion,
       dspinventory_chf_datecommissioned,
       dspinventory_chf_devicefirmwareversion,
       dspinventory_chf_devicefirmwareversionstatus,
       dspinventory_chf_devicegbcsversion,
       dspinventory_chf_deviceid,
       dspinventory_chf_devicemanufacturer,
       dspinventory_chf_devicemodel,
       dspinventory_chf_devicestatus,
       dspinventory_chf_devicetype,
       dspinventory_chf_esmevariant,
       dspinventory_chf_exportmpan,
       dspinventory_chf_hanvariant,
       dspinventory_chf_importmpxn,
       dspinventory_chf_propertyfilter_addressidentifier,
       dspinventory_chf_propertyfilter_postcode,
       dspinventory_chf_s1sp,
       dspinventory_chf_smetschtsversion,
       dspinventory_chf_secondaryimportmpan,
       dspinventory_chf_uprn,
       dspinventory_esme_cplstatus,
       dspinventory_esme_cspregion,
       dspinventory_esme_datecommissioned,
       dspinventory_esme_devicefirmwareversion,
       dspinventory_esme_devicefirmwareversionstatus,
       dspinventory_esme_devicegbcsversion,
       dspinventory_esme_deviceid,
       dspinventory_esme_devicemanufacturer,
       dspinventory_esme_devicemodel,
       dspinventory_esme_devicestatus,
       dspinventory_esme_devicetype,
       dspinventory_esme_esmevariant,
       dspinventory_esme_exportmpan,
       dspinventory_esme_hanvariant,
       dspinventory_esme_importmpxn,
       dspinventory_esme_propertyfilter_addressidentifier,
       dspinventory_esme_propertyfilter_postcode,
       dspinventory_esme_s1sp,
       dspinventory_esme_smetschtsversion,
       dspinventory_esme_secondaryimportmpan,
       dspinventory_esme_uprn,
       dspinventory_gpf_cplstatus,
       dspinventory_gpf_cspregion,
       dspinventory_gpf_datecommissioned,
       dspinventory_gpf_devicefirmwareversion,
       dspinventory_gpf_devicefirmwareversionstatus,
       dspinventory_gpf_devicegbcsversion,
       dspinventory_gpf_deviceid,
       dspinventory_gpf_devicemanufacturer,
       dspinventory_gpf_devicemodel,
       dspinventory_gpf_devicestatus,
       dspinventory_gpf_devicetype,
       dspinventory_gpf_esmevariant,
       dspinventory_gpf_exportmpan,
       dspinventory_gpf_hanvariant,
       dspinventory_gpf_importmpxn,
       dspinventory_gpf_propertyfilter_addressidentifier,
       dspinventory_gpf_propertyfilter_postcode,
       dspinventory_gpf_s1sp,
       dspinventory_gpf_smetschtsversion,
       dspinventory_gpf_secondaryimportmpan,
       dspinventory_gpf_uprn,
       dspinventory_gsme_cplstatus,
       dspinventory_gsme_cspregion,
       dspinventory_gsme_datecommissioned,
       dspinventory_gsme_devicefirmwareversion,
       dspinventory_gsme_devicefirmwareversionstatus,
       dspinventory_gsme_devicegbcsversion,
       dspinventory_gsme_deviceid,
       dspinventory_gsme_devicemanufacturer,
       dspinventory_gsme_devicemodel,
       dspinventory_gsme_devicestatus,
       dspinventory_gsme_devicetype,
       dspinventory_gsme_esmevariant,
       dspinventory_gsme_exportmpan,
       dspinventory_gsme_hanvariant,
       dspinventory_gsme_importmpxn,
       dspinventory_gsme_propertyfilter_addressidentifier,
       dspinventory_gsme_propertyfilter_postcode,
       dspinventory_gsme_s1sp,
       dspinventory_gsme_smetschtsversion,
       dspinventory_gsme_secondaryimportmpan,
       dspinventory_gsme_uprn,
       dspinventory_ihd_cplstatus,
       dspinventory_ihd_cspregion,
       dspinventory_ihd_datecommissioned,
       dspinventory_ihd_devicefirmwareversion,
       dspinventory_ihd_devicefirmwareversionstatus,
       dspinventory_ihd_devicegbcsversion,
       dspinventory_ihd_deviceid,
       dspinventory_ihd_devicemanufacturer,
       dspinventory_ihd_devicemodel,
       dspinventory_ihd_devicestatus,
       dspinventory_ihd_devicetype,
       dspinventory_ihd_esmevariant,
       dspinventory_ihd_exportmpan,
       dspinventory_ihd_hanvariant,
       dspinventory_ihd_importmpxn,
       dspinventory_ihd_propertyfilter_addressidentifier,
       dspinventory_ihd_propertyfilter_postcode,
       dspinventory_ihd_s1sp,
       dspinventory_ihd_smetschtsversion,
       dspinventory_ihd_secondaryimportmpan,
       dspinventory_ihd_uprn,
       dspinventory_ppmid_cplstatus,
       dspinventory_ppmid_cspregion,
       dspinventory_ppmid_datecommissioned,
       dspinventory_ppmid_devicefirmwareversion,
       dspinventory_ppmid_devicefirmwareversionstatus,
       dspinventory_ppmid_devicegbcsversion,
       dspinventory_ppmid_deviceid,
       dspinventory_ppmid_devicemanufacturer,
       dspinventory_ppmid_devicemodel,
       dspinventory_ppmid_devicestatus,
       dspinventory_ppmid_devicetype,
       dspinventory_ppmid_esmevariant,
       dspinventory_ppmid_exportmpan,
       dspinventory_ppmid_hanvariant,
       dspinventory_ppmid_importmpxn,
       dspinventory_ppmid_propertyfilter_addressidentifier,
       dspinventory_ppmid_propertyfilter_postcode,
       dspinventory_ppmid_s1sp,
       dspinventory_ppmid_smetschtsversion,
       dspinventory_ppmid_secondaryimportmpan,
       dspinventory_ppmid_uprn,
       deviceid,
       mpxn,
       count(etlchange)
FROM aws_s3_stage2_extracts.stage2_temp_inv_full
GROUP BY dspinventory_cad_cplstatus,
       dspinventory_cad_cspregion,
       dspinventory_cad_datecommissioned,
       dspinventory_cad_devicefirmwareversion,
       dspinventory_cad_devicefirmwareversionstatus,
       dspinventory_cad_devicegbcsversion,
       dspinventory_cad_deviceid,
       dspinventory_cad_devicemanufacturer,
       dspinventory_cad_devicemodel,
       dspinventory_cad_devicestatus,
       dspinventory_cad_devicetype,
       dspinventory_cad_esmevariant,
       dspinventory_cad_exportmpan,
       dspinventory_cad_hanvariant,
       dspinventory_cad_importmpxn,
       dspinventory_cad_propertyfilter_addressidentifier,
       dspinventory_cad_propertyfilter_postcode,
       dspinventory_cad_s1sp,
       dspinventory_cad_smetschtsversion,
       dspinventory_cad_secondaryimportmpan,
       dspinventory_cad_uprn,
       dspinventory_chf_cplstatus,
       dspinventory_chf_cspregion,
       dspinventory_chf_datecommissioned,
       dspinventory_chf_devicefirmwareversion,
       dspinventory_chf_devicefirmwareversionstatus,
       dspinventory_chf_devicegbcsversion,
       dspinventory_chf_deviceid,
       dspinventory_chf_devicemanufacturer,
       dspinventory_chf_devicemodel,
       dspinventory_chf_devicestatus,
       dspinventory_chf_devicetype,
       dspinventory_chf_esmevariant,
       dspinventory_chf_exportmpan,
       dspinventory_chf_hanvariant,
       dspinventory_chf_importmpxn,
       dspinventory_chf_propertyfilter_addressidentifier,
       dspinventory_chf_propertyfilter_postcode,
       dspinventory_chf_s1sp,
       dspinventory_chf_smetschtsversion,
       dspinventory_chf_secondaryimportmpan,
       dspinventory_chf_uprn,
       dspinventory_esme_cplstatus,
       dspinventory_esme_cspregion,
       dspinventory_esme_datecommissioned,
       dspinventory_esme_devicefirmwareversion,
       dspinventory_esme_devicefirmwareversionstatus,
       dspinventory_esme_devicegbcsversion,
       dspinventory_esme_deviceid,
       dspinventory_esme_devicemanufacturer,
       dspinventory_esme_devicemodel,
       dspinventory_esme_devicestatus,
       dspinventory_esme_devicetype,
       dspinventory_esme_esmevariant,
       dspinventory_esme_exportmpan,
       dspinventory_esme_hanvariant,
       dspinventory_esme_importmpxn,
       dspinventory_esme_propertyfilter_addressidentifier,
       dspinventory_esme_propertyfilter_postcode,
       dspinventory_esme_s1sp,
       dspinventory_esme_smetschtsversion,
       dspinventory_esme_secondaryimportmpan,
       dspinventory_esme_uprn,
       dspinventory_gpf_cplstatus,
       dspinventory_gpf_cspregion,
       dspinventory_gpf_datecommissioned,
       dspinventory_gpf_devicefirmwareversion,
       dspinventory_gpf_devicefirmwareversionstatus,
       dspinventory_gpf_devicegbcsversion,
       dspinventory_gpf_deviceid,
       dspinventory_gpf_devicemanufacturer,
       dspinventory_gpf_devicemodel,
       dspinventory_gpf_devicestatus,
       dspinventory_gpf_devicetype,
       dspinventory_gpf_esmevariant,
       dspinventory_gpf_exportmpan,
       dspinventory_gpf_hanvariant,
       dspinventory_gpf_importmpxn,
       dspinventory_gpf_propertyfilter_addressidentifier,
       dspinventory_gpf_propertyfilter_postcode,
       dspinventory_gpf_s1sp,
       dspinventory_gpf_smetschtsversion,
       dspinventory_gpf_secondaryimportmpan,
       dspinventory_gpf_uprn,
       dspinventory_gsme_cplstatus,
       dspinventory_gsme_cspregion,
       dspinventory_gsme_datecommissioned,
       dspinventory_gsme_devicefirmwareversion,
       dspinventory_gsme_devicefirmwareversionstatus,
       dspinventory_gsme_devicegbcsversion,
       dspinventory_gsme_deviceid,
       dspinventory_gsme_devicemanufacturer,
       dspinventory_gsme_devicemodel,
       dspinventory_gsme_devicestatus,
       dspinventory_gsme_devicetype,
       dspinventory_gsme_esmevariant,
       dspinventory_gsme_exportmpan,
       dspinventory_gsme_hanvariant,
       dspinventory_gsme_importmpxn,
       dspinventory_gsme_propertyfilter_addressidentifier,
       dspinventory_gsme_propertyfilter_postcode,
       dspinventory_gsme_s1sp,
       dspinventory_gsme_smetschtsversion,
       dspinventory_gsme_secondaryimportmpan,
       dspinventory_gsme_uprn,
       dspinventory_ihd_cplstatus,
       dspinventory_ihd_cspregion,
       dspinventory_ihd_datecommissioned,
       dspinventory_ihd_devicefirmwareversion,
       dspinventory_ihd_devicefirmwareversionstatus,
       dspinventory_ihd_devicegbcsversion,
       dspinventory_ihd_deviceid,
       dspinventory_ihd_devicemanufacturer,
       dspinventory_ihd_devicemodel,
       dspinventory_ihd_devicestatus,
       dspinventory_ihd_devicetype,
       dspinventory_ihd_esmevariant,
       dspinventory_ihd_exportmpan,
       dspinventory_ihd_hanvariant,
       dspinventory_ihd_importmpxn,
       dspinventory_ihd_propertyfilter_addressidentifier,
       dspinventory_ihd_propertyfilter_postcode,
       dspinventory_ihd_s1sp,
       dspinventory_ihd_smetschtsversion,
       dspinventory_ihd_secondaryimportmpan,
       dspinventory_ihd_uprn,
       dspinventory_ppmid_cplstatus,
       dspinventory_ppmid_cspregion,
       dspinventory_ppmid_datecommissioned,
       dspinventory_ppmid_devicefirmwareversion,
       dspinventory_ppmid_devicefirmwareversionstatus,
       dspinventory_ppmid_devicegbcsversion,
       dspinventory_ppmid_deviceid,
       dspinventory_ppmid_devicemanufacturer,
       dspinventory_ppmid_devicemodel,
       dspinventory_ppmid_devicestatus,
       dspinventory_ppmid_devicetype,
       dspinventory_ppmid_esmevariant,
       dspinventory_ppmid_exportmpan,
       dspinventory_ppmid_hanvariant,
       dspinventory_ppmid_importmpxn,
       dspinventory_ppmid_propertyfilter_addressidentifier,
       dspinventory_ppmid_propertyfilter_postcode,
       dspinventory_ppmid_s1sp,
       dspinventory_ppmid_smetschtsversion,
       dspinventory_ppmid_secondaryimportmpan,
       dspinventory_ppmid_uprn,
       deviceid,
       mpxn);


select count(distinct(deviceid)) from aws_s3_stage2_extracts.stage2_temp_inv_full;
select count(distinct(deviceid)) from aws_s3_stage2_extracts.stage2_temp_inv_raw;
select count(distinct(deviceid)) from ref_smart_inventory;


select count(*) from aws_s3_stage2_extracts.stage2_temp_inv_full;
select count(*) from aws_s3_stage2_extracts.stage2_temp_inv_raw;
select count(*) from ref_smart_inventory;

insert into temp_smart_inventory
select
                dspinventory_cad_cplstatus ::varchar(15),
                dspinventory_cad_cspregion ::varchar(15),
                dspinventory_cad_datecommissioned ::timestamp ,
                dspinventory_cad_devicefirmwareversion ::varchar(15),
                dspinventory_cad_devicefirmwareversionstatus ::varchar(15),
                dspinventory_cad_devicegbcsversion ::varchar(15),
                dspinventory_cad_deviceid ::varchar(100),
                dspinventory_cad_devicemanufacturer ::varchar(15),
                dspinventory_cad_devicemodel ::varchar(15),
                dspinventory_cad_devicestatus ::varchar(15),
                dspinventory_cad_devicetype ::varchar(15),
                dspinventory_cad_esmevariant ::varchar(15),
                dspinventory_cad_exportmpan ::bigint ,
                dspinventory_cad_hanvariant ::varchar(15),
                dspinventory_cad_importmpxn ::bigint ,
                dspinventory_cad_propertyfilter_addressidentifier ::varchar(100),
                dspinventory_cad_propertyfilter_postcode ::varchar(15),
                dspinventory_cad_s1sp ::varchar(15),
                dspinventory_cad_smetschtsversion ::varchar(15),
                dspinventory_cad_secondaryimportmpan ::bigint ,
                dspinventory_cad_uprn ::varchar(15),
                dspinventory_chf_cplstatus ::varchar(15),
                dspinventory_chf_cspregion ::varchar(15),
                dspinventory_chf_datecommissioned ::timestamp ,
                dspinventory_chf_devicefirmwareversion ::varchar(15),
                dspinventory_chf_devicefirmwareversionstatus ::varchar(15),
                dspinventory_chf_devicegbcsversion ::varchar(15),
                dspinventory_chf_deviceid ::varchar(100),
                dspinventory_chf_devicemanufacturer ::varchar(15),
                dspinventory_chf_devicemodel ::varchar(15),
                dspinventory_chf_devicestatus ::varchar(50),
                dspinventory_chf_devicetype ::varchar(15),
                dspinventory_chf_esmevariant ::varchar(15),
                dspinventory_chf_exportmpan ::bigint ,
                dspinventory_chf_hanvariant ::varchar(15),
                dspinventory_chf_importmpxn ::bigint ,
                dspinventory_chf_propertyfilter_addressidentifier ::varchar(100),
                dspinventory_chf_propertyfilter_postcode ::varchar(15),
                dspinventory_chf_s1sp ::varchar(15),
                dspinventory_chf_smetschtsversion ::varchar(15),
                dspinventory_chf_secondaryimportmpan ::bigint ,
                dspinventory_chf_uprn ::bigint ,
                dspinventory_esme_cplstatus ::varchar(15),
                dspinventory_esme_cspregion ::varchar(15),
                dspinventory_esme_datecommissioned ::timestamp ,
                dspinventory_esme_devicefirmwareversion ::varchar(15),
                dspinventory_esme_devicefirmwareversionstatus ::varchar(15),
                dspinventory_esme_devicegbcsversion ::varchar(15),
                dspinventory_esme_deviceid ::varchar(100),
                dspinventory_esme_devicemanufacturer ::varchar(15),
                dspinventory_esme_devicemodel ::varchar(15),
                dspinventory_esme_devicestatus ::varchar(50),
                dspinventory_esme_devicetype ::varchar(15),
                dspinventory_esme_esmevariant ::varchar(15),
                dspinventory_esme_exportmpan ::bigint ,
                dspinventory_esme_hanvariant ::varchar(15),
                dspinventory_esme_importmpxn ::bigint ,
                dspinventory_esme_propertyfilter_addressidentifier ::varchar(100),
                dspinventory_esme_propertyfilter_postcode ::varchar(15),
                dspinventory_esme_s1sp ::varchar(15),
                dspinventory_esme_smetschtsversion ::varchar(15),
                dspinventory_esme_secondaryimportmpan ::bigint ,
                dspinventory_esme_uprn ::bigint ,
                dspinventory_gpf_cplstatus ::varchar(15),
                dspinventory_gpf_cspregion ::varchar(15),
                dspinventory_gpf_datecommissioned ::timestamp ,
                dspinventory_gpf_devicefirmwareversion ::varchar(15),
                dspinventory_gpf_devicefirmwareversionstatus ::varchar(15),
                dspinventory_gpf_devicegbcsversion ::varchar(15),
                dspinventory_gpf_deviceid ::varchar(100),
                dspinventory_gpf_devicemanufacturer ::varchar(15),
                dspinventory_gpf_devicemodel ::varchar(15),
                dspinventory_gpf_devicestatus ::varchar(50),
                dspinventory_gpf_devicetype ::varchar(15),
                dspinventory_gpf_esmevariant ::varchar(15),
                dspinventory_gpf_exportmpan ::bigint ,
                dspinventory_gpf_hanvariant ::varchar(15),
                dspinventory_gpf_importmpxn ::bigint ,
                dspinventory_gpf_propertyfilter_addressidentifier ::varchar(100),
                dspinventory_gpf_propertyfilter_postcode ::varchar(15),
                dspinventory_gpf_s1sp ::varchar(15),
                dspinventory_gpf_smetschtsversion ::varchar(15) ,
                dspinventory_gpf_secondaryimportmpan ::bigint ,
                dspinventory_gpf_uprn ::bigint ,
                dspinventory_gsme_cplstatus ::varchar(15),
                dspinventory_gsme_cspregion ::varchar(15),
                dspinventory_gsme_datecommissioned ::timestamp ,
                dspinventory_gsme_devicefirmwareversion ::varchar(15),
                dspinventory_gsme_devicefirmwareversionstatus ::varchar(15),
                dspinventory_gsme_devicegbcsversion ::varchar(15),
                dspinventory_gsme_deviceid ::varchar(100),
                dspinventory_gsme_devicemanufacturer ::varchar(15),
                dspinventory_gsme_devicemodel ::varchar(15),
                dspinventory_gsme_devicestatus ::varchar(50),
                dspinventory_gsme_devicetype ::varchar(15),
                dspinventory_gsme_esmevariant ::varchar(15),
                dspinventory_gsme_exportmpan ::bigint ,
                dspinventory_gsme_hanvariant ::varchar(15),
                dspinventory_gsme_importmpxn ::bigint ,
                dspinventory_gsme_propertyfilter_addressidentifier ::varchar(100),
                dspinventory_gsme_propertyfilter_postcode ::varchar(15),
                dspinventory_gsme_s1sp ::varchar(15),
                dspinventory_gsme_smetschtsversion ::varchar(15),
                dspinventory_gsme_secondaryimportmpan ::bigint ,
                dspinventory_gsme_uprn ::bigint ,
                dspinventory_ihd_cplstatus ::varchar(15),
                dspinventory_ihd_cspregion ::varchar(15),
                dspinventory_ihd_datecommissioned ::timestamp ,
                dspinventory_ihd_devicefirmwareversion ::varchar(15),
                dspinventory_ihd_devicefirmwareversionstatus ::varchar(15),
                dspinventory_ihd_devicegbcsversion ::varchar(15),
                dspinventory_ihd_deviceid ::varchar(100),
                dspinventory_ihd_devicemanufacturer ::varchar(15),
                dspinventory_ihd_devicemodel ::varchar(15),
                dspinventory_ihd_devicestatus ::varchar(50),
                dspinventory_ihd_devicetype ::varchar(15),
                dspinventory_ihd_esmevariant ::varchar(15),
                dspinventory_ihd_exportmpan ::bigint ,
                dspinventory_ihd_hanvariant ::varchar(15),
                dspinventory_ihd_importmpxn ::bigint ,
                dspinventory_ihd_propertyfilter_addressidentifier ::varchar(100),
                dspinventory_ihd_propertyfilter_postcode ::varchar(15),
                dspinventory_ihd_s1sp ::varchar(15),
                dspinventory_ihd_smetschtsversion ::varchar(15),
                dspinventory_ihd_secondaryimportmpan ::bigint ,
                dspinventory_ihd_uprn ::bigint ,
                dspinventory_ppmid_cplstatus ::varchar(15),
                dspinventory_ppmid_cspregion ::varchar(15),
                dspinventory_ppmid_datecommissioned ::timestamp ,
                dspinventory_ppmid_devicefirmwareversion ::varchar(15),
                dspinventory_ppmid_devicefirmwareversionstatus ::varchar(15),
                dspinventory_ppmid_devicegbcsversion ::varchar(15),
                dspinventory_ppmid_deviceid ::varchar(100),
                dspinventory_ppmid_devicemanufacturer ::varchar(15),
                dspinventory_ppmid_devicemodel ::varchar(15),
                dspinventory_ppmid_devicestatus ::varchar(50),
                dspinventory_ppmid_devicetype ::varchar(15),
                dspinventory_ppmid_esmevariant ::varchar(15),
                dspinventory_ppmid_exportmpan ::bigint ,
                dspinventory_ppmid_hanvariant ::varchar(15),
                dspinventory_ppmid_importmpxn ::bigint ,
                dspinventory_ppmid_propertyfilter_addressidentifier ::varchar(100),
                dspinventory_ppmid_propertyfilter_postcode ::varchar(15),
                dspinventory_ppmid_s1sp ::varchar(15),
                dspinventory_ppmid_smetschtsversion ::varchar(15),
                dspinventory_ppmid_secondaryimportmpan ::bigint ,
                dspinventory_ppmid_uprn ::bigint ,
                deviceid ::varchar(100),
                mpxn  ::bigint ,
              etlchange::timestamp  as etlchange
		from aws_s3_stage2_extracts.stage2_temp_inv_full;

create table temp_smart_inventory
(
	dspinventory_cad_cplstatus varchar(15),
	dspinventory_cad_cspregion varchar(15),
	dspinventory_cad_datecommissioned timestamp encode az64,
	dspinventory_cad_devicefirmwareversion varchar(15),
	dspinventory_cad_devicefirmwareversionstatus varchar(15),
	dspinventory_cad_devicegbcsversion varchar(15),
	dspinventory_cad_deviceid varchar(100),
	dspinventory_cad_devicemanufacturer varchar(15),
	dspinventory_cad_devicemodel varchar(15),
	dspinventory_cad_devicestatus varchar(50),
	dspinventory_cad_devicetype varchar(15),
	dspinventory_cad_esmevariant varchar(15),
	dspinventory_cad_exportmpan bigint encode az64,
	dspinventory_cad_hanvariant varchar(15),
	dspinventory_cad_importmpxn bigint encode az64,
	dspinventory_cad_propertyfilter_addressidentifier varchar(100),
	dspinventory_cad_propertyfilter_postcode varchar(15),
	dspinventory_cad_s1sp varchar(15),
	dspinventory_cad_smetschtsversion varchar(15),
	dspinventory_cad_secondaryimportmpan bigint encode az64,
	dspinventory_cad_uprn varchar(15),
	dspinventory_chf_cplstatus varchar(15),
	dspinventory_chf_cspregion varchar(15),
	dspinventory_chf_datecommissioned timestamp encode az64,
	dspinventory_chf_devicefirmwareversion varchar(15),
	dspinventory_chf_devicefirmwareversionstatus varchar(15),
	dspinventory_chf_devicegbcsversion varchar(15),
	dspinventory_chf_deviceid varchar(100),
	dspinventory_chf_devicemanufacturer varchar(15),
	dspinventory_chf_devicemodel varchar(15),
	dspinventory_chf_devicestatus varchar(50),
	dspinventory_chf_devicetype varchar(15),
	dspinventory_chf_esmevariant varchar(15),
	dspinventory_chf_exportmpan bigint encode az64,
	dspinventory_chf_hanvariant varchar(15),
	dspinventory_chf_importmpxn bigint encode az64,
	dspinventory_chf_propertyfilter_addressidentifier varchar(100),
	dspinventory_chf_propertyfilter_postcode varchar(15),
	dspinventory_chf_s1sp varchar(15),
	dspinventory_chf_smetschtsversion varchar(15),
	dspinventory_chf_secondaryimportmpan bigint encode az64,
	dspinventory_chf_uprn varchar(15),
	dspinventory_esme_cplstatus varchar(15),
	dspinventory_esme_cspregion varchar(15),
	dspinventory_esme_datecommissioned timestamp encode az64,
	dspinventory_esme_devicefirmwareversion varchar(15),
	dspinventory_esme_devicefirmwareversionstatus varchar(15),
	dspinventory_esme_devicegbcsversion varchar(15),
	dspinventory_esme_deviceid varchar(100),
	dspinventory_esme_devicemanufacturer varchar(15),
	dspinventory_esme_devicemodel varchar(15),
	dspinventory_esme_devicestatus varchar(50),
	dspinventory_esme_devicetype varchar(15),
	dspinventory_esme_esmevariant varchar(15),
	dspinventory_esme_exportmpan bigint encode az64,
	dspinventory_esme_hanvariant varchar(15),
	dspinventory_esme_importmpxn bigint encode az64,
	dspinventory_esme_propertyfilter_addressidentifier varchar(100),
	dspinventory_esme_propertyfilter_postcode varchar(15),
	dspinventory_esme_s1sp varchar(15),
	dspinventory_esme_smetschtsversion varchar(15),
	dspinventory_esme_secondaryimportmpan bigint encode az64,
	dspinventory_esme_uprn varchar(15),
	dspinventory_gpf_cplstatus varchar(15),
	dspinventory_gpf_cspregion varchar(15),
	dspinventory_gpf_datecommissioned timestamp encode az64,
	dspinventory_gpf_devicefirmwareversion varchar(15),
	dspinventory_gpf_devicefirmwareversionstatus varchar(15),
	dspinventory_gpf_devicegbcsversion varchar(15),
	dspinventory_gpf_deviceid varchar(100),
	dspinventory_gpf_devicemanufacturer varchar(15),
	dspinventory_gpf_devicemodel varchar(15),
	dspinventory_gpf_devicestatus varchar(50),
	dspinventory_gpf_devicetype varchar(15),
	dspinventory_gpf_esmevariant varchar(15),
	dspinventory_gpf_exportmpan bigint encode az64,
	dspinventory_gpf_hanvariant varchar(15),
	dspinventory_gpf_importmpxn bigint encode az64,
	dspinventory_gpf_propertyfilter_addressidentifier varchar(100),
	dspinventory_gpf_propertyfilter_postcode varchar(15),
	dspinventory_gpf_s1sp varchar(15),
	dspinventory_gpf_smetschtsversion varchar(15),
	dspinventory_gpf_secondaryimportmpan bigint encode az64,
	dspinventory_gpf_uprn varchar(15),
	dspinventory_gsme_cplstatus varchar(15),
	dspinventory_gsme_cspregion varchar(15),
	dspinventory_gsme_datecommissioned timestamp encode az64,
	dspinventory_gsme_devicefirmwareversion varchar(15),
	dspinventory_gsme_devicefirmwareversionstatus varchar(15),
	dspinventory_gsme_devicegbcsversion varchar(15),
	dspinventory_gsme_deviceid varchar(100),
	dspinventory_gsme_devicemanufacturer varchar(15),
	dspinventory_gsme_devicemodel varchar(15),
	dspinventory_gsme_devicestatus varchar(50),
	dspinventory_gsme_devicetype varchar(15),
	dspinventory_gsme_esmevariant varchar(15),
	dspinventory_gsme_exportmpan bigint encode az64,
	dspinventory_gsme_hanvariant varchar(15),
	dspinventory_gsme_importmpxn bigint encode az64,
	dspinventory_gsme_propertyfilter_addressidentifier varchar(100),
	dspinventory_gsme_propertyfilter_postcode varchar(15),
	dspinventory_gsme_s1sp varchar(15),
	dspinventory_gsme_smetschtsversion varchar(15),
	dspinventory_gsme_secondaryimportmpan bigint encode az64,
	dspinventory_gsme_uprn varchar(15),
	dspinventory_ihd_cplstatus varchar(15),
	dspinventory_ihd_cspregion varchar(15),
	dspinventory_ihd_datecommissioned timestamp encode az64,
	dspinventory_ihd_devicefirmwareversion varchar(15),
	dspinventory_ihd_devicefirmwareversionstatus varchar(15),
	dspinventory_ihd_devicegbcsversion varchar(15),
	dspinventory_ihd_deviceid varchar(100),
	dspinventory_ihd_devicemanufacturer varchar(15),
	dspinventory_ihd_devicemodel varchar(15),
	dspinventory_ihd_devicestatus varchar(50),
	dspinventory_ihd_devicetype varchar(15),
	dspinventory_ihd_esmevariant varchar(15),
	dspinventory_ihd_exportmpan bigint encode az64,
	dspinventory_ihd_hanvariant varchar(15),
	dspinventory_ihd_importmpxn bigint encode az64,
	dspinventory_ihd_propertyfilter_addressidentifier varchar(100),
	dspinventory_ihd_propertyfilter_postcode varchar(15),
	dspinventory_ihd_s1sp varchar(15),
	dspinventory_ihd_smetschtsversion varchar(15),
	dspinventory_ihd_secondaryimportmpan bigint encode az64,
	dspinventory_ihd_uprn varchar(15),
	dspinventory_ppmid_cplstatus varchar(15),
	dspinventory_ppmid_cspregion varchar(15),
	dspinventory_ppmid_datecommissioned timestamp encode az64,
	dspinventory_ppmid_devicefirmwareversion varchar(15),
	dspinventory_ppmid_devicefirmwareversionstatus varchar(15),
	dspinventory_ppmid_devicegbcsversion varchar(15),
	dspinventory_ppmid_deviceid varchar(100),
	dspinventory_ppmid_devicemanufacturer varchar(15),
	dspinventory_ppmid_devicemodel varchar(15),
	dspinventory_ppmid_devicestatus varchar(50),
	dspinventory_ppmid_devicetype varchar(15),
	dspinventory_ppmid_esmevariant varchar(15),
	dspinventory_ppmid_exportmpan bigint encode az64,
	dspinventory_ppmid_hanvariant varchar(15),
	dspinventory_ppmid_importmpxn bigint encode az64,
	dspinventory_ppmid_propertyfilter_addressidentifier varchar(100),
	dspinventory_ppmid_propertyfilter_postcode varchar(15),
	dspinventory_ppmid_s1sp varchar(15),
	dspinventory_ppmid_smetschtsversion varchar(15),
	dspinventory_ppmid_secondaryimportmpan bigint encode az64,
	dspinventory_ppmid_uprn bigint encode az64,
	deviceid varchar(100),
	mpxn bigint encode az64,
	etlchange timestamp encode az64
)
;

alter table temp_smart_inventory owner to igloo
;

select
                dspinventory_cad_cplstatus ::varchar(15),
                dspinventory_cad_cspregion ::varchar(15),
                dspinventory_cad_datecommissioned ::timestamp ,
                dspinventory_cad_devicefirmwareversion ::varchar(15),
                dspinventory_cad_devicefirmwareversionstatus ::varchar(15),
                dspinventory_cad_devicegbcsversion ::varchar(15),
                dspinventory_cad_deviceid ::varchar(100),
                dspinventory_cad_devicemanufacturer ::varchar(15),
                dspinventory_cad_devicemodel ::varchar(15),
                dspinventory_cad_devicestatus ::varchar(15),
                dspinventory_cad_devicetype ::varchar(15),
                dspinventory_cad_esmevariant ::varchar(15),
                dspinventory_cad_exportmpan ::bigint ,
                dspinventory_cad_hanvariant ::varchar(15),
                dspinventory_cad_importmpxn ::bigint ,
                dspinventory_cad_propertyfilter_addressidentifier ::varchar(100),
                dspinventory_cad_propertyfilter_postcode ::varchar(15),
                dspinventory_cad_s1sp ::varchar(15),
                dspinventory_cad_smetschtsversion ::varchar(15),
                dspinventory_cad_secondaryimportmpan ::bigint ,
                dspinventory_cad_uprn ::varchar(15),
                dspinventory_chf_cplstatus ::varchar(15),
                dspinventory_chf_cspregion ::varchar(15),
                dspinventory_chf_datecommissioned ::timestamp ,
                dspinventory_chf_devicefirmwareversion ::varchar(15),
                dspinventory_chf_devicefirmwareversionstatus ::varchar(15),
                dspinventory_chf_devicegbcsversion ::varchar(15),
                dspinventory_chf_deviceid ::varchar(100),
                dspinventory_chf_devicemanufacturer ::varchar(15),
                dspinventory_chf_devicemodel ::varchar(15),
                dspinventory_chf_devicestatus ::varchar(50),
                dspinventory_chf_devicetype ::varchar(15),
                dspinventory_chf_esmevariant ::varchar(15),
                dspinventory_chf_exportmpan ::bigint ,
                dspinventory_chf_hanvariant ::varchar(15),
                dspinventory_chf_importmpxn ::bigint ,
                dspinventory_chf_propertyfilter_addressidentifier ::varchar(100),
                dspinventory_chf_propertyfilter_postcode ::varchar(15),
                dspinventory_chf_s1sp ::varchar(15),
                dspinventory_chf_smetschtsversion ::varchar(15),
                dspinventory_chf_secondaryimportmpan ::bigint ,
                dspinventory_chf_uprn ::bigint ,
                dspinventory_esme_cplstatus ::varchar(15),
                dspinventory_esme_cspregion ::varchar(15),
                dspinventory_esme_datecommissioned ::timestamp ,
                dspinventory_esme_devicefirmwareversion ::varchar(15),
                dspinventory_esme_devicefirmwareversionstatus ::varchar(15),
                dspinventory_esme_devicegbcsversion ::varchar(15),
                dspinventory_esme_deviceid ::varchar(100),
                dspinventory_esme_devicemanufacturer ::varchar(15),
                dspinventory_esme_devicemodel ::varchar(15),
                dspinventory_esme_devicestatus ::varchar(50),
                dspinventory_esme_devicetype ::varchar(15),
                dspinventory_esme_esmevariant ::varchar(15),
                dspinventory_esme_exportmpan ::bigint ,
                dspinventory_esme_hanvariant ::varchar(15),
                dspinventory_esme_importmpxn ::bigint ,
                dspinventory_esme_propertyfilter_addressidentifier ::varchar(100),
                dspinventory_esme_propertyfilter_postcode ::varchar(15),
                dspinventory_esme_s1sp ::varchar(15),
                dspinventory_esme_smetschtsversion ::varchar(15),
                dspinventory_esme_secondaryimportmpan ::bigint ,
                dspinventory_esme_uprn ::bigint ,
                dspinventory_gpf_cplstatus ::varchar(15),
                dspinventory_gpf_cspregion ::varchar(15),
                dspinventory_gpf_datecommissioned ::timestamp ,
                dspinventory_gpf_devicefirmwareversion ::varchar(15),
                dspinventory_gpf_devicefirmwareversionstatus ::varchar(15),
                dspinventory_gpf_devicegbcsversion ::varchar(15),
                dspinventory_gpf_deviceid ::varchar(100),
                dspinventory_gpf_devicemanufacturer ::varchar(15),
                dspinventory_gpf_devicemodel ::varchar(15),
                dspinventory_gpf_devicestatus ::varchar(50),
                dspinventory_gpf_devicetype ::varchar(15),
                dspinventory_gpf_esmevariant ::varchar(15),
                dspinventory_gpf_exportmpan ::bigint ,
                dspinventory_gpf_hanvariant ::varchar(15),
                dspinventory_gpf_importmpxn ::bigint ,
                dspinventory_gpf_propertyfilter_addressidentifier ::varchar(100),
                dspinventory_gpf_propertyfilter_postcode ::varchar(15),
                dspinventory_gpf_s1sp ::varchar(15),
                dspinventory_gpf_smetschtsversion ::varchar(15) ,
                dspinventory_gpf_secondaryimportmpan ::bigint ,
                dspinventory_gpf_uprn ::bigint ,
                dspinventory_gsme_cplstatus ::varchar(15),
                dspinventory_gsme_cspregion ::varchar(15),
                dspinventory_gsme_datecommissioned ::timestamp ,
                dspinventory_gsme_devicefirmwareversion ::varchar(15),
                dspinventory_gsme_devicefirmwareversionstatus ::varchar(15),
                dspinventory_gsme_devicegbcsversion ::varchar(15),
                dspinventory_gsme_deviceid ::varchar(100),
                dspinventory_gsme_devicemanufacturer ::varchar(15),
                dspinventory_gsme_devicemodel ::varchar(15),
                dspinventory_gsme_devicestatus ::varchar(50),
                dspinventory_gsme_devicetype ::varchar(15),
                dspinventory_gsme_esmevariant ::varchar(15),
                dspinventory_gsme_exportmpan ::bigint ,
                dspinventory_gsme_hanvariant ::varchar(15),
                dspinventory_gsme_importmpxn ::bigint ,
                dspinventory_gsme_propertyfilter_addressidentifier ::varchar(100),
                dspinventory_gsme_propertyfilter_postcode ::varchar(15),
                dspinventory_gsme_s1sp ::varchar(15),
                dspinventory_gsme_smetschtsversion ::varchar(15),
                dspinventory_gsme_secondaryimportmpan ::bigint ,
                dspinventory_gsme_uprn ::bigint ,
                dspinventory_ihd_cplstatus ::varchar(15),
                dspinventory_ihd_cspregion ::varchar(15),
                dspinventory_ihd_datecommissioned ::timestamp ,
                dspinventory_ihd_devicefirmwareversion ::varchar(15),
                dspinventory_ihd_devicefirmwareversionstatus ::varchar(15),
                dspinventory_ihd_devicegbcsversion ::varchar(15),
                dspinventory_ihd_deviceid ::varchar(100),
                dspinventory_ihd_devicemanufacturer ::varchar(15),
                dspinventory_ihd_devicemodel ::varchar(15),
                dspinventory_ihd_devicestatus ::varchar(50),
                dspinventory_ihd_devicetype ::varchar(15),
                dspinventory_ihd_esmevariant ::varchar(15),
                dspinventory_ihd_exportmpan ::bigint ,
                dspinventory_ihd_hanvariant ::varchar(15),
                dspinventory_ihd_importmpxn ::bigint ,
                dspinventory_ihd_propertyfilter_addressidentifier ::varchar(100),
                dspinventory_ihd_propertyfilter_postcode ::varchar(15),
                dspinventory_ihd_s1sp ::varchar(15),
                dspinventory_ihd_smetschtsversion ::varchar(15),
                dspinventory_ihd_secondaryimportmpan ::bigint ,
                dspinventory_ihd_uprn ::bigint ,
                dspinventory_ppmid_cplstatus ::varchar(15),
                dspinventory_ppmid_cspregion ::varchar(15),
                dspinventory_ppmid_datecommissioned ::timestamp ,
                dspinventory_ppmid_devicefirmwareversion ::varchar(15),
                dspinventory_ppmid_devicefirmwareversionstatus ::varchar(15),
                dspinventory_ppmid_devicegbcsversion ::varchar(15),
                dspinventory_ppmid_deviceid ::varchar(100),
                dspinventory_ppmid_devicemanufacturer ::varchar(15),
                dspinventory_ppmid_devicemodel ::varchar(15),
                dspinventory_ppmid_devicestatus ::varchar(50),
                dspinventory_ppmid_devicetype ::varchar(15),
                dspinventory_ppmid_esmevariant ::varchar(15),
                dspinventory_ppmid_exportmpan ::bigint ,
                dspinventory_ppmid_hanvariant ::varchar(15),
                dspinventory_ppmid_importmpxn ::bigint ,
                dspinventory_ppmid_propertyfilter_addressidentifier ::varchar(100),
                dspinventory_ppmid_propertyfilter_postcode ::varchar(15),
                dspinventory_ppmid_s1sp ::varchar(15),
                dspinventory_ppmid_smetschtsversion ::varchar(15),
                dspinventory_ppmid_secondaryimportmpan ::bigint ,
                dspinventory_ppmid_uprn ::bigint ,
                deviceid ::varchar(100),
                mpxn  ::bigint ,
              etlchange::timestamp  as etlchange
            from  public.ref_smart_inventory_raw