-- auto-generated definition
drop table ref_calculated_daily_customer_file;
create table ref_calculated_daily_customer_file
(
    account_id                bigint distkey,
    elec_ssd                  timestamp,
    gas_ssd                   timestamp,
    elec_ed                   timestamp,
    gas_ed                    timestamp,
    acc_ssd                   timestamp,
    acc_ed                    timestamp,
    num_elec_mpns             bigint,
    num_gas_mpns              bigint,
    first_canc_elec_ssd       timestamp,
    first_canc_elec_sed       timestamp,
    first_canc_gas_ssd        timestamp,
    first_canc_gas_sed        timestamp,
    num_canc_elec_mpns        bigint,
    num_canc_gas_mpns         bigint,
    eac_industry              double precision,
    aq_industry               double precision,
    eac_igloo_ca              double precision,
    eac_igloo_ca_source       varchar(256),
    aq_igloo_ca               double precision,
    aq_igloo_ca_source        varchar(256),
    reg_pay_amount            double precision,
    reg_pay_amount_ex_wu      double precision,
    wu_amount                 double precision,
    wu_this_year              boolean,
    reg_pay_date              double precision,
    projected_savings         double precision,
    balance                   double precision,
    elec_annual_spend         double precision,
    gas_annual_spend          double precision,
    elec_reg_status           varchar(13),
    elec_cancellation_reason  varchar(65535),
    gas_reg_status            varchar(13),
    gas_cancellation_reason   varchar(65535),
    elec_loss_type            varchar(3),
    gas_loss_type             varchar(3),
    supply_type               varchar(5),
    account_status            varchar(13),
    account_loss_type         varchar(3),
    gsp                       varchar(255),
    ldz                       varchar(255),
    wl0_date                  timestamp,
    wl1_date                  timestamp,
    home_move_in              boolean,
    gas_et1                   boolean,
    elec_et1                  boolean,
    signup_channel            varchar(255),
    signup_channel_secondary  varchar(255),
    broker_name               varchar(255),
    broker_urn                varchar(255),
    signup_date               timestamp,
    campaign                  varchar(16383),
    quoted_eac                double precision,
    quoted_aq                 double precision,
    quoted_total_spend        double precision,
    first_payment_success     boolean,
    num_payments              bigint,
    latest_dd_received_date   timestamp,
    payment_in_last_month     boolean,
    outcode                   varchar(255),
    first_bill_date           timestamp,
    first_bill_type           varchar(11),
    latest_bill_date          timestamp,
    latest_bill_type          varchar(12),
    num_bills                 bigint,
    first_final_bill_date     timestamp,
    first_final_refund_date   timestamp,
    monthly_bill_date         integer,
    next_bill_date            timestamp,
    first_bill_effective_date timestamp,
    bill_perf_1               bigint,
    bill_perf_2               bigint,
    bill_perf_3               bigint,
    occupier_account          boolean,
    days_as_occ_acc           bigint,
    etlchange                 timestamp
)
    diststyle key
    sortkey (account_id);

alter table ref_calculated_daily_customer_file
    owner to igloo;

-- auto-generated definition
create table ref_calculated_sales_report
(
    supply_contract_id  bigint distkey,
    ensek_id            bigint,
    signup_channel      varchar(255),
    secondary_channel   varchar(255),
    broker_name         varchar(255),
    broker_urn          varchar(255),
    signup_date         timestamp,
    campaign            varchar(16383),
    account_status      varchar(13),
    cancellation_reason varchar(65535),
    supply_type         varchar(255),
    partner_name        varchar(16383),
    etlchange           timestamp
)
    diststyle key
    sortkey (supply_contract_id, ensek_id);

alter table ref_calculated_sales_report
    owner to igloo;


-- auto-generated definition
create table ref_calculated_metering_report
(
    mpr                        bigint,
    msn                        varchar(255),
    account_id                 bigint distkey,
    fuel_type                  varchar(1),
    meterpoint_ssd             timestamp,
    meterpoint_sed             timestamp,
    meterpoint_status          varchar(13),
    acc_mp_ssd                 timestamp,
    acc_mp_sed                 timestamp,
    acc_mp_status              varchar(13),
    meter_status               varchar(255),
    meter_install_date         timestamp,
    meter_removed_date         timestamp,
    meter_type                 varchar(255),
    meter_location             varchar(255),
    meter_mechanism            varchar(255),
    num_registers              bigint,
    num_dials                  varchar(255),
    ssc                        varchar(255),
    mop_mam                    varchar(255),
    mop_mam_effective_date     timestamp,
    old_mop_mam                varchar(65535),
    old_supplier_mop_mam       varchar(255),
    mex_occurred               varchar(7),
    mex_date                   timestamp,
    f_read_date                timestamp,
    f_read_dc                  varchar(16),
    f_read_other_source        varchar(65535),
    f_read_other_status        varchar(16),
    i_read_date                timestamp,
    i_read_dc                  varchar(16),
    i_read_other_source        varchar(65535),
    i_read_other_status        varchar(16),
    sed_read_date              timestamp,
    sed_read_dc                varchar(16),
    sed_read_other_source      varchar(65535),
    sed_read_other_status      varchar(16),
    ssd_read_date              timestamp,
    ssd_read_dc                varchar(16),
    ssd_read_other_source      varchar(65535),
    ssd_read_other_status      varchar(16),
    eac_aq_in                  varchar(7),
    eac_aq_effective_date      timestamp,
    supply_status              varchar(255),
    gas_imperial_indicator     varchar(255),
    gain_supplier              varchar(255),
    neg_state_occurred         boolean,
    num_valid_actual_reads     bigint,
    num_inv_actual_reads       bigint,
    first_valid_actual         date,
    first_invalid_actual       date,
    latest_valid_actual        date,
    latest_invalid_actual      date,
    latest_invalid_actual_type varchar(16),
    etlchange                  timestamp
)
    diststyle key
    sortkey (mpr, msn, account_id);

alter table ref_calculated_metering_report
    owner to igloo;

-- AURORA --------------------------------------------------------------------
-- auto-generated definition
drop table ref_calculated_daily_customer_file;
create table ref_calculated_daily_customer_file
(
    account_id                bigint,
    elec_ssd                  timestamp,
    gas_ssd                   timestamp,
    elec_ed                   timestamp,
    gas_ed                    timestamp,
    acc_ssd                   timestamp,
    acc_ed                    timestamp,
    num_elec_mpns             bigint,
    num_gas_mpns              bigint,
    first_canc_elec_ssd       timestamp,
    first_canc_elec_sed       timestamp,
    first_canc_gas_ssd        timestamp,
    first_canc_gas_sed        timestamp,
    num_canc_elec_mpns        bigint,
    num_canc_gas_mpns         bigint,
    eac_industry              double precision,
    aq_industry               double precision,
    eac_igloo_ca              double precision,
    eac_igloo_ca_source       varchar(256),
    aq_igloo_ca               double precision,
    aq_igloo_ca_source        varchar(256),
    reg_pay_amount            double precision,
    reg_pay_amount_ex_wu      double precision,
    wu_amount                 double precision,
    wu_this_year              boolean,
    reg_pay_date              double precision,
    projected_savings         double precision,
    balance                   double precision,
    elec_annual_spend         double precision,
    gas_annual_spend          double precision,
    elec_reg_status           varchar(13),
    elec_cancellation_reason  varchar(255),
    gas_reg_status            varchar(13),
    gas_cancellation_reason   varchar(255),
    elec_loss_type            varchar(3),
    gas_loss_type             varchar(3),
    supply_type               varchar(5),
    account_status            varchar(13),
    account_loss_type         varchar(3),
    gsp                       varchar(255),
    ldz                       varchar(255),
    wl0_date                  timestamp,
    wl1_date                  timestamp,
    home_move_in              boolean,
    gas_et1                   boolean,
    elec_et1                  boolean,
    signup_channel            varchar(255),
    signup_channel_secondary  varchar(255),
    broker_name               varchar(255),
    broker_urn                varchar(255),
    signup_date               timestamp,
    campaign                  varchar(255),
    quoted_eac                double precision,
    quoted_aq                 double precision,
    quoted_total_spend        double precision,
    first_payment_success     boolean,
    num_payments              bigint,
    latest_dd_received_date   timestamp,
    payment_in_last_month     boolean,
    outcode                   varchar(255),
    first_bill_date           timestamp,
    first_bill_type           varchar(11),
    latest_bill_date          timestamp,
    latest_bill_type          varchar(12),
    num_bills                 bigint,
    first_final_bill_date     timestamp,
    first_final_refund_date   timestamp,
    monthly_bill_date         integer,
    next_bill_date            timestamp,
    first_bill_effective_date timestamp,
    bill_perf_1               bigint,
    bill_perf_2               bigint,
    bill_perf_3               bigint,
    occupier_account          boolean,
    days_as_occ_acc           bigint,
    etlchange                 timestamp
);

create index ref_calculated_daily_customer_file_account_id_index
    on ref_calculated_daily_customer_file (account_id);

