-- Report Name: sense-uos-customers-interested-in-focus-groups
--Trello Link: https://trello.com/c/6CjU4t03/51-sense-uos-customers-interested-in-focus-groups

select case when mmh.email is null then 'Invalid/No data'
            else '' end as valid_email_id,
       e.*,
       mmh.* from
     temp_email e
left outer join
(
select
--        u.id         as user_id,
       u.email,
       left(addr.postcode, len(addr.postcode) - 3) postcode,
--        su.external_id,
--       max(ac.status),
       coalesce((select sum(reg.registers_eacaq)
                             from ref_meterpoints mp
                                    inner join ref_meters m
                                      on m.account_id = mp.account_id and m.meter_point_id = mp.meter_point_id and
                                         m.removeddate is null
                                    inner join ref_registers reg
                                      on reg.account_id = mp.account_id and reg.meter_id = m.meter_id
                             where mp.account_id = su.external_id
                               and mp.meterpointtype = 'G'
                               and (mp.supplyenddate is null or mp.supplyenddate >= getdate())
                             group by mp.account_id), 0)                                    as aq,
       coalesce((select sum(reg.registers_eacaq)
                     from ref_meterpoints mp
                            inner join ref_meters m
                              on m.account_id = mp.account_id and m.meter_point_id = mp.meter_point_id and
                                 m.removeddate is null
                            inner join ref_registers reg
                              on reg.account_id = mp.account_id and reg.meter_id = m.meter_id
                     where mp.account_id = su.external_id
                       and mp.meterpointtype = 'E'
                       and (mp.supplyenddate is null or mp.supplyenddate >= getdate())
                     group by mp.account_id), 0)                                    as eac,
       max(case
             when att.attribute_description = 'The preferred temperature a user sets their thermostat'
                     then attribute_value
               end) as thermostat,
       max(case
             when att.attribute_description = 'Does the property have a hot water tank' then attribute_value
               end) as hotwatertank,
       max(case
             when att.attribute_description = 'Age of the boiler within a property' then attribute_value
               end) as ageofboiler,
       max(case
             when att.attribute_description = 'Type of heating at a property' then attribute_value
               end) as typeofheating,
       max(case
             when att.attribute_description = 'Number of bedrooms in a property' then attribute_value
               end) as numberofbedrooms,
       max(case
             when att.attribute_description = 'How a home is typically heated' then attribute_value
               end) as typicallyheated,
       max(case
             when att.attribute_description = 'Type of heating control at a property' then attribute_value
               end) as typeofheatingcontrol,
       max(case
             when att.attribute_description = 'Type of house' then attribute_value
               end) as typeofhouse,
       max(case
             when att.attribute_description = 'Age of house' then attribute_value
               end) as ageofhouse,
       max(case
             when att.attribute_description = 'Number of bedrooms in a property' then attribute_value
               end) as numberofbedrooms,
       max(case
             when att.attribute_description = 'Age of the boiler within a property' then attribute_value
               end) as ageofboiler,
       max(case
             when att.attribute_description = 'What appliances are within a certain property\'s kitchen' then attribute_custom_value
               end) as whatappliances,
       max(case
             when att.attribute_description = 'Ages of the residents that live with a User' then attribute_custom_value
               end) as agesofpeople
from ref_cdb_supply_contracts su
       inner join ref_cdb_addresses addr on su.supply_address_id = addr.id
       inner join ref_cdb_user_permissions up on su.id = up.permissionable_id and permission_level = 0
                                                   and permissionable_type = 'App\\SupplyContract'
       inner join ref_cdb_users u on u.id = up.user_id
       left outer join ref_account_status ac on ac.account_id = su.external_id
       left outer join ref_cdb_attributes at on (
                                                    (at.entity_id = up.user_id AND at.entity_type = 'App\\User')
                                                      OR
                                                    (at.entity_id = su.supply_address_id AND at.entity_type = 'App\\Address')
                                                    )
                                                  and at.effective_to is null
       left outer join ref_cdb_attribute_types att on att.id = at.attribute_type_id and att.effective_to is null
       left outer join ref_cdb_attribute_values av
         on av.attribute_type_id = at.attribute_type_id and at.attribute_value_id = av.id
              and at.attribute_value_id is not null
       left outer join ref_cdb_survey_questions sq on sq.attribute_type_id = att.id
       left outer join ref_cdb_survey_category sc on sc.id = sq.survey_category_id
       left outer join (select user_id, survey_id
                        from ref_cdb_survey_response
                        where survey_id = 1
                        group by user_id, survey_id) sr on sr.user_id = up.user_id
where
--     su.supply_address_id = 867 and
--     u.id = 18094 and
--     sr.user_id is null and
        ac.status = 'Live' and
u.email in ('Ozxavi@gmail.com',
'tara.mann@me.com',
'mark.wreford@gmail.com',
'robertjsills@yahoo.co.uk',
'rlduffy@dsl.pipex.com',
'fazenumber4@yahoo.co.uk',
'Matthewleigh23@outlook.com',
'wesley.bleach@hotmail.co.uk',
'cindysharman@gmail.com',
'lochlan.macdonald@cityofglondon.gov.uk',
'derek13hearne@gmail.com',
'chawkesm@gmail.com',
'esmejaye1@gmail.com',
'sminamioka@gmail.com',
'steven@room14.co.uk',
'Harry.woodington@gmail.com',
'andrewrclark90@gmail.com',
'peeldamian@mac.com',
'Davydward@yahoo.co.uk',
'Karinhanna@sky.com',
'jimpage@me.com',
'mariamahon27@yahoo.com',
'oneadr@yahoo.co.uk',
'ewanmcintosh@Sky.com',
'utilities@de-borde.co.uk',
'carmantrathen@icloud.com',
'mockingbird11@virginmedia.com',
'jdp@liverpool.ac.uk',
'djhistory@gmail.com',
'neil@mellerick.co.uk',
'aaron.warren@howardhunt.com',
'geraldsheehan5@gmail.com',
'chris.sheppard@yahoo.com',
'petergibson@iname.com',
'Fiser@me.com',
'neil.edwards567@gmail.com',
'Leahalice156@gmail.com',
'Alynicholson@aol.com',
'michael_streets@yahoo.com',
'david.pert@sky.com',
'dan_si_vio@yahoo.com',
'jamescave@outlook.com',
'suzy.wuzy@hotmail.co.uk',
'philipdavidge@gmail.com',
'ziyakhan@hotmail.com',
'Markscott.ee@gmail.com',
'rob.isitt@hotmail.co.uk',
'jonathanphilpotts@me.com',
'gillen_j@hotmail.com',
'mark@kelmhouse.co.uk',
'jeankruger64@gmail.com',
'amcdon41177@aol.com',
'toneoldbone@gmail.com',
'david_wetton@yahoo.com',
'rickygilb@btinternet.com',
'Nicola.christian@hotmail.co.uk',
'garry@heatcare.com',
'gjholland125@gmail.com',
'henrypugh82@gmail.com',
'cazza_sanderson@yahoo.co.uk',
'dawn.chatwin@sky.com',
'colinandrews600@gmail.com',
'neilfox@gmail.com',
'olly@thinkmovechange.com',
'david.mcdonnell@btinternet.com',
'Juliajb@hotmail.co.uk',
'geoffgoff@virginmedia.com',
'rebecca_adams_87@hotmail.co.uk',
'James.ramsden@gmail.com',
'skulla_funga@hotmail.com',
'paulchandler23@gmail.com',
'nick@theschroeders.co.uk',
'lcshiels@gmail.com',
'theresamac32@gmail.com',
'duncan.banks@open.ac.uk',
'Peter.mackenzie@ntlworld.com',
'bazsyd@hotmail.com',
'markcharles1980@gmail.com',
'mlawrence13130@gmail.com',
'victorialewin@hotmail.co.uk',
'itlane@outlook.com',
'contact@spiky.fr',
'lyndsay_mcnicol@hotmail.com',
'18094',
'me@seanharrison.co.uk',
'amit.bhute@gmail.com',
'sammi_jo86@hotmail.com',
'katie.osborne89@yahoo.com',
'nick@nickwarren.net',
'janice.mahoney@allianz.co.uk',
'lidbert@ntlworld.com',
'chris.bradbury@gmail.com',
'punchard@les-gaz.net',
'dickonroberts@gmail.com',
'gail.blackman@me.com',
'liz.hewitt2012@btinternet.com',
'zoe.sorotos@gmail.com',
'dave.stejonda@gmail.com',
'offduty@orchard21.plus.com',
'barbara@polglaze.plus.com',
'richard_brazier@hotmail.com',
's.jmilligan@sky.comans.j',
'patrickdunne@yahoo.com',
'jandahole@gmail.com',
'kitchong@hotmail.co.uk',
'ken@keggie.com',
'redmen1963@gmail.com',
'denniswhitelondon@gmail.com',
'carolejohnson@ymail.com',
'Energy@kitchenfitter.co.uk',
'blossevans@yahoo.co.uk',
'kaz529@aol.com',
'mistermallet@hotmail.com',
'p.whitneypdr@gmail.com',
'hj-oldiesinthesticks@uwclub.net',
'rke925@yahoo.co.uk',
'pendredsigns@gmail.com',
'deharding1@btinternet.com',
'allen.playford@btinternet.com',
'kieroncreagh@outlook.com',
'ian_t_smart@hotmail.com',
'duncanwesterman@talktalk.net',
'Ianpotter160@btinternet.com',
'pauljesmith33@gmail.com',
'Sarahddykes@gmail.com',
'k.harcourtsmith@btinternet.com',
'normarees49@hotmail.co.uk',
'dommatthews@gmail.com',
'Rhianlbaker@gmail.com',
'jsnoon@virginmedia.com',
'pkm321@live.co.uk',
'peter.anderson@Adelphigroup.com',
'Christophermorgan1@sky.com',
'nickyluff@icloud.com',
'emmanuel.lebecq@me.com',
'joyma@hushmail.com',
'mrotuhey@gmail.com',
'Suzanne.white97@ntlworld.com',
'jamie_cooper@btinternet.com',
'scott@scotthunt.co.uk',
'adealtry50@gmail.com',
'maskilljohn@yahoo.co.uk',
'Gemmahowell66@yahoo.co.uk',
'suehooper323@btinternet.com',
'29339 graham.stephenson2014@gmail.com',
'sdcarroll849@btinternet.com',
'andreactownend@sky.com',
'sandpbushnell@gmail.com',
'tcb.beb@btinternet.com',
'rogers.harry@gmail.com',
'Craig.tanner@icloud.com',
'thehooks8@gmail.com',
'daniel.m.williams@hotmail.com',
'jam.jar@sky.com',
'ian6hurst@gmail.com',
'mogue2@hotmail.co.uk',
'Michaelrowden@hotmail.co.uk',
'jdgriffiths608@hotmail.com',
'zhaninam@gmail.com',
'Mooreaneta200@gmail.com',
'eltonvaughan@gmail.com',
'200006740@btconnect.com',
'nickhollisuk@yahoo.co.uk',
'gary.barnes1@btinternet.com',
'Jeng871@btinternet.com',
'n.matthews-graves@hotmail.co.uk',
'steve.h.partridge@ntlworld.com',
'karen.way1@ntlworld.com',
'STEVE@RAVENESQUE.CO.UK',
'athertp@yahoo.co.uk',
'juliestrong@btinternet.com',
'David109lawrence@gmail.com',
'garybollands@gmail.com',
'jimbirdzz@netscape.net',
'sarahlynnette55@yahoo.co.uk',
'Karl.halliday35@gmail.com',
'paul@paultelco.com',
'thomas.white2772@gmail.com',
'cransom61@hotmail.com',
'nsweitz@gmail.com',
'jbsquared@btinternet.com',
'a.jtorquay@gmail.com',
'dilysaudrey8@gmail.com',
'noncore@corlessfamily.com',
'tonyhand123@btinterne.tcom',
'junethackrah@me.com',
'Rdrayton210@gmail.com',
'isallt.nantlle@gmail.com',
'Pragnaa@aol.com',
'philbuck83@hotmail.co.uk',
'kevin@vivvid.co.uk',
'dannmacuk@aol.com',
'chrs.holland@gmail.com',
'terrycrone@hotmail.com',
'jhnaismith@gmail.com',
'graley@gainsoft.co.uk',
'sarah.whitehouse@6kbw.com',
'sarboykay@hotmail.com',
'richardsonmichael242@gmail.com',
'brianr77@blueyonder.co.uk',
'alheard79@gmail.com',
'johnanstiss@hotmail.com',
'elaine.sharp84@gmail.com',
'jamie.kind26@gmail.com',
'Thistledoo1@gmail.com',
'ruthpitt12@gmail.com',
'dlmajor@sky.com',
'bairey89@gmail.com',
'caroleiw@yahoo.com',
'juliawhiting24@icloud.com',
'gpiazzon@hotmail.co.uk',
'32626 jonathansoper@hotmail.com',
'nienawidzetuska@gmail.com',
'cmbc.stengel@gmail.com',
'djhspooner@gmail.com',
'marcel.vanheijzen@yahoo.co.uk',
'gillkf@gmail.com',
'martinstiksel@gmail.com',
'zchrislongman@hotmail.com',
'kennyjhowse@gmail.com',
'Smudge9446@gmail.com',
'ma.kaulics@gmail.com',
'traceywong@hotmail.co.uk',
'Margaret.tabbener@gmail.com077658',
'Chasfyoung@googlemail.com',
'marcus.swalwell@gmail.com',
'joanna.gallimore@yahoo.com',
'ash.hansla@outlook.com',
'ashley_rossington@hotmail.com',
'debbietear70@gmail.com',
'jconnick@msn.com',
'jason.jutla@gmail.com',
'Angiehael@googlemail.com',
'June@juneburrough.co.uk',
'neilshouse@gmail.com',
'chad.h.saunders+mse@gmail.com',
'richardandabbie@gmail.com',
'briggselectrical@yahoo.co.uk',
'richard.windred@btinternet.com',
'crdia801@aol.com',
'jalavender@practicalactions.co.uk',
'Kellyboy69@sky.com',
'jonayling@gmail.com',
'tofugeek@gmail.com',
'1967kevin@gmail.com',
'tony.pagett@blueyonder.co.uk',
'basicexposure@icloud.com',
'Ian_parfitt@hotmail.co.uk',
'b.turner93@ntlworld.com',
'juwil.symington@gmail.com',
'lyn.e.crawford@gmail.com',
'mechapman@blueyonder.co.uk',
'gillandpearson@hotmail.com',
'dentpatrick@hotmail.com',
'plumtreec@gmail.com',
'adrian.wigham@yahoo.co.uk',
'carlymw253@gmail.com',
'brian.baker15@btinternet.com',
'rmh@holdom.net',
'alvie.mahmud@hotmail.co.uk',
'si.willcox@gmail.com',
'c.callanan@homecall.co.uk',
'rod.grinsted2@gmail.com',
'carolynmccann@gmail.com',
'tompop01@madasafish.com',
'nivek.retsel@gmail.com',
'jasonnicki5@hotmail.com',
'lloydmartyn@hotmail.com',
'Clark465@btinternet.com',
'32920 mayporter300@gmail .com',
'Paulrowlie@gmail.com',
'dltc.davidlane@gmail.com',
'benedict.mcguigan@gmail.com',
'ruthclemiw@hotmail.com',
'tonecat101@outlook.com',
'jmtaylor948@gmail.com',
'vstokeley@hotmail.com',
'alistair@burmark.co.uk',
'gilly_taylor21@hotmail.co.uk',
'tonester666@gmail.com',
'sharon.wilson@hotmail.com',
'hayley@littleun.com',
'jon@setty.co.uk',
'ccbam83@gmail.com',
'm.cartledge@sky.com',
'Beckywrigley@icloud.com',
'rachelembleton75@gmail.com',
'garyorton71@gmail.com',
'roughlini@icloud.com',
'jwdigby@hotmail.com',
'peterhs@doctors.org.uk',
'Ljcspencer@hotmail.co.uk',
'shell_1_@hotmail.com',
'Lexdev@icloud.com',
'Mary-annriley@hotmail.com',
'gagvasquez@gmail.com',
'neil@atkinson.name',
'ezragarcia91@zoho.com',
'streamfraser@btinternet.com',
'Mail@joeellis.co.uk',
'lucilla@blueyonder.co.uk',
'westfield.am@googlemail.com',
'maidment123@icloud.com',
'meintrow@hotmail.co.uk',
'graham1946@hotmail.co.uk',
'vbansal@live.co.uk',
'r.kasher@sky.com',
'Beverleyfarnish@icloud.com',
'christopherjamesbircham@gmail.com',
'tomgareh@hotmail.com',
'davetarr1@gmail.com',
'junepenfold@gmail.com',
'matabolix@hotmail.com',
'martingillpost@gmail.com',
'donrogers@sky.com',
'donna.brindle@sky.com',
'david.madle@ricardo.com',
'olayinkamosadomi@gmail.com',
'benskirrow111@gmail.com',
'lornalalji@gmail.com',
'yemenmike@aol.com',
'Luciajoni@hotmail.co.uk',
'Marctomschofield@hotmail.com',
'Niki.pearce@live.co.uk',
'Kaarenremington @hotmail.co.uk',
'tonyknife1970@googlemail.com',
'Jillsshines@gmail.com',
'na_mcdonald@icloud.com',
'sipuncher@gmail.com',
'seb_squeak@live.com',
'burstowr@aol.com',
'stevebold@blueyonder.co.uk',
'sueruss.stewart@gmail.com',
'samedwards2207@gmail.com',
'igloo@mjbk.uk',
'mitch.paris@live.co.uk',
'sharon_alva@yahoo.co.uk',
'mpagram@icloud.com',
'mnalista@hotmail.co.uk',
'peter@peterjagger.co.uk',
'pauldavidcrouch@gmail.com',
's.palmerralph@outlook.com',
'trevor.may@btinternet.com',
'aabr05@icloud.com',
'jkilmister@gmail.com',
'aamirbc2000@yahoo.com',
'36667 a.milton@virgin.net',
'michaelgwatson77@gmail.com',
'pwd41284@yahoo.co.uk',
'loshears@gmail.com',
'zannaw@hotmail.com',
'rleigh.mail@gmail.com',
'cduffain@gmail.com',
'alandeunice@yahoo.com',
'martyncooper1@sky.com',
'jack_samways@hotmail.com',
'keeble269@gmail.com',
'sallyhalls@gmail.com',
'6156 kevin@cleasbyonline.co.uk',
'mrsideshowjack@gmail.com',
'barrywhlr@gmail.com',
'kewal.rai75@gmail.com',
'raymond.booth@gmail.com',
'allan.battersby@btopenworld.com',
'kategreeves@hotmail.com',
'duncangunstone@hotmail.com',
'dpm661@gmail.com',
'rupertcapleton@yahoo.com',
'adedayobenson@yahoo.com',
'charlotte.burn2012@gmail.com',
'Kerrypratt96@gmail.com',
'scottpunton@hotmail.co.uk',
'pbclarke21@gmail.com',
'Ben.dingley@hot.co.uk',
'turnbull.kieran@gmail.com',
'Gbarrat122@gmailcom',
'swampington@hotmail.com',
'boho1212@gmail.com',
'Matt_whitton4@hotmail.com',
'a.thompson135@btinternet.com',
'burts.bike@gmail.com',
'holbrow.chris@gmail.com',
'mwhogg74@gmail.com',
'tony_wilkinson2003@yahoo.co.uk',
'Rmpooley@gmail.com',
'mfthomas@lineone.net',
'midimode@btinternet.com',
'mnsomersltd@googlemail.com',
'"Lyndhurst", 8 Mount Vernon Road, Barnsley, South Yorkshire, S70 4DJ.',
'petardim914@gmail.com',
'Kristina.gorkovskaya@gmail.com',
'Gkh416@hotmail.com',
'anastasia.cunningham@ntlworld.com',
'jaymereaves@gmail.com',
'sylwia@nationwideproduce.com',
'timothymjharper@gmail.com',
'alistermacnaught@yahoo.com',
'johnmelrose42@icloud.com',
'jameslittmann@gmail.com',
'les_survey@btinternet.com',
'nirmaank@hotmail.com',
'williammathieson1@outlook.com',
'mike1939davis@gmail.com',
'A/C 35989 cp@cgp.me.uk',
'ian@beerandcurry.me.uk',
'colroselloyd@btinternet.com',
'adrian.gamble@gmx.com',
'clare.a.hancock@gmail.com',
'malcolmsaunders@btinternet.com',
'valerie.hazan@gmail.com',
'nige.bamford@gmail.com',
'claudneves@gmail.com',
'patricia@pattigran.plus.com',
'c.greenway@ntlworld.com',
'2775, colin.littler@yahoo.co.uk',
'peter.ellis70@ntlworld.com',
'hfagon@gmail.com',
'paul@rodgerwillco.com',
'sbillett@gmail.com',
'mick_hewitt@btconnect.com',
'mick@donmcmath.org',
'fry.a@ntlworld.com',
'weknowwhereyoulive@gmail.com',
'dustin.lees@outlook.com',
'carl_stevenson@mac.com',
'karmanchung@gmail.com',
'tonymmoore@btinternet.com',
'elimron10@ntlworld.com',
'Trlawnm@gmail.com',
'Samanthaleenders@hotmail.co.uk',
'davidsables@gmail.com',
'herwagner@hotmail.com',
'Janet.nock@gmail.com',
'malcolmwatson986@yahoo.co',
'andy.hepworth@hotmail.co.uk',
'maxim.armour@gmail.com',
'Liz.gearing@btinternet.com',
'clairerogers77@gmail.com',
'edwardbaers@hotmail.co.uk',
'r1mmels@hotmail.com',
'Sharonmilner880@gmail.com',
'Barryandjanewyton@sky.com',
'terry400@gmail.com',
'petermarsh68@gmail.com',
'mikec@homemail.com',
'crusoesleap@yahoo.co.uk07979741007',
'natalieholloway@hotmail.co.uk',
'iammayhew@icloud.com',
'tony@58lions.co.uk',
'dave@davegarner.co.uk',
'robert1960rolls@gmail.com',
'keenemh@aol.com',
'bruceduncan158@yahoo.com',
'hamish.stewart@gmail.com',
'katherine.zambaldi@gmail.com',
'srmt@btinternet.com',
'simonpannett@aol.com',
'roddy.gilly@gmail.com',
'ajmalras@gmail.co.uk',
'peterwilcoxcm@gmail.com',
'fosworld@hotmail.com',
'clairenrich@gmail.com',
'lynandbob@virginmedia.com',
'alantrotman@hotmail.co.uk',
'JDChapman2000@GMail.com',
'robert_j_simmonds@hotmail.co.uk',
'robsdixon@gmail.com',
'mandpshopping@btinternet.com',
'tony@gentone.co.uk',
'janfrodsham@hotmail.com',
'osmond266@yahoo.co.uk',
'Jennfinch@btinternet.com',
'lasher1539@hotmail.com',
'hawleyian@btinternet.com',
'bberry259@gmail.com',
'mdfleming@virginmedia.com',
'nishmashah@hotmail.com',
'andy.kemp1@ntlworld.com',
'judit.pelikan@gmail.com',
'jskilly1@aol.com',
'peterturner@hotmail.com',
'c.walker@hotmail.co.uk',
'amccuaig@brightred.com',
'rujutathegreat@hotmail.com',
'iangb_2000@yahoo.co.uk',
'jimonhismobile@gmail.com',
'geoff_bowron@hotmail.com',
'witchypoo1949@googlemail.com',
'Bob_page@talk21.com',
'yockney@yahoo.com',
'leprechaun201@hotmail.com',
'prmaidment@gmail.com',
'elp79.ep@googlemail.com',
'milesdj287@googlemail.com',
'mr@egrouse.com',
'ppspdh@aol.com',
'paulevans@postinbox.com',
'darren-petherick@hotmail.co.uk',
'vinny59@hotmail.co.uk',
'davidtmartin@icloud.com',
'pdl300@hotmail.com',
'mmarkk_2@hotmail.com',
'stephenshuttleworth@hotmail.com',
'annetod@icloud.com',
'beezle3@yahoo.com',
'craig.bufton@outlook.com',
'ajlaing@acplc.net',
'james84hare@gmail.com',
'johnlikeman@yahoo.co.uk',
'irimsarwar@gmail.com',
'patterson_j2@sky.com',
'Admiremandaza1@gmail.com',
'Sswinzy1@gmail.com',
'Castellanoslorenzo@gmail.com',
'Scott.motion@live.co.uk',
'katerina.woolhouse@gmail.com',
'russellprice@me.com',
'tomjoshw1997@gmail.com',
'nicolas.rose@sony.com',
'w',
'yxmk551k@gmail.com',
'pilar.matji95@gmail.com',
'matt752@hotmail.com',
'29 Cavendish Drive, TN2 5DU',
'crippsfarm@gmail.com',
'Tonyturton@btinternet.com',
'arben290@gmail.com',
'hamish_anderson@btinternet.com',
'37036 avrilcherry@gmail.com',
'br_marks@hotmail.com',
'sezam.uk@gmail.com',
'andy_powles@hotmail.com',
'georginov@yahoo.com',
'Jamiewhmltn@gmail.com',
'graeme.aldridge@gmail.com',
'thomasparker32@gmx.com',
'lcg8477@gmail.com',
'lionel7bell@yahoo.co.uk',
'Scvddw@yahoo.co.uk',
'rebecca_hewes@hotmail.com',
'gemmapidsley@hotmail.co.uk',
'emilycharlotte11@gmail.com',
'gareth.lewis@astrazeneca.com',
'georgejedwards@gmail.com',
'belindajholley@gmail.com',
'hss_sidhu@yahoo.co.uk',
'pete@williamsresidence.co.uk',
'29607 vixbeale@gmail.com',
'woodwardtp@gmail.com',
'M.cumberlidge@btopenworld.com',
'b.taylor26@sky.com',
'kazgood39@yahoo.co.uk',
'dorchestermike@outlook.com',
'7998 mooneen@aol.com',
'littlefollies@hotmail.co.uk',
'colin@martyn-meade.co.uk',
'robert.jones@standardsbg.com',
'dhwynne@hotmail.com',
'Meganfoste@aol.com',
'unclepete100@gmail.com',
'alfredshipp65@hotmail.com',
'youngysk41@gmail.com',
'jamesmcneice61@hotmail.com',
'elonagreenaway@btinternet.com',
'gemmaeade@hotmail.com',
'blu_tirohl@hotmail.com',
'Aagoren',
'lisacstamp@gmail.com',
'PRAFUL_MAKWANA@HOTMAIL.CO.UK',
'Davidzim@btinternet.com',
'kathyb12@hotmail.co.uk',
'terry.seaber@ntlworld.com',
'1955.sp@gmail.com',
'lynne1804@gmail.com',
'Justin_allenuk@yahoo.co.uk',
'louis.otway@gmail.com',
'aussiestew@talk21.com',
'bblockley1@btinternet.com',
'kate@mjsmortgages.co.uk',
'roly.ryan1@outlook.com',
'nigel.cronin@gmail.com',
'Keith.heaviside@rocketmail.com',
'johnm@mitch.uk.com',
'alexandra.maria2606@gmail.com',
'anarayandookie@gmail.com',
'trev101@live.co.uk',
'Antony.bird@newsprinters.co.uk',
'annie@anniegriffith.co.uk',
'Fraserk@virginmedia.com',
'poppajon43@gmail.com',
'Mazpez@hotmail.com',
'uglyson64@gmail.com',
'gc.brown@ntlworld.com',
'Everitt-jones@hotmail. Com',
'robinhard@btinternet.com',
'joshcarter1998@icloud.com',
'clairecrudge@btinternet.com',
'Rick.duffy@outlook.com',
'tomatr250@gmail.com',
'sandeep49@yahoo.com',
'peter.hackman06@gmail.com',
'paul@meridenlodge.co.uk',
'jezwhite1@hotmail.com',
'damanning.manning9@gmail.com',
'1bobbygibbs@gmail.com',
'danny@qvs-uk.com',
'phil.edgell@gmail.com',
'jeannedarrington@hotmail.com',
'lizzie_brown@hotmail.com',
'acmedway42@googlemail.com',
'Macdoylefamily@gmail.com',
'francescolog67@gmail.com',
'hazzer999@gmail.com',
'p.onions@btinternet.com',
'chrisrwebber@gmail.com',
'leigh.bidmead@gmail.com',
'mandcblackburn@googlemail.com',
'mike@smalley.biz',
'mrusselljones@gmail.com',
'barrettsallyanne@gmail.com',
'janettebowen@hotmail.com',
'Paul.0.jones@btinternet.com',
'drsajenkins@btinternet.com',
'huangheruby86@gmail.com',
'Claire.ferrao@gmail.com',
'andyburlow@gmail.com',
'Matt.sj.gardner@gmail.com',
'mjackson2@talktalk.net',
'ruthylangford@gmail.com',
'stephenwlord@gmail.com',
'wiggins.debbie@gmail.com',
'steve.eade@gmx.com',
'jacekowski@jacekowski.org',
'jinobs@gmail.com',
'Clare.hunter2@ntlworld.com',
'jjalder@hotmail.com',
'andy.saxton@icloud.com',
'steven.hardstaff@ucyfc.co.uk',
'phgoodwin23@gmail.com',
'lj.weir@btinternet.com',
'mikecook@blueyonder.co.uk',
'sophiestradins@gmail.com',
'kim.allyson@ntlworld.com',
'owen!@mdx.ac.uk',
'FJBowers@msn.com',
'thejanx@live.co.uk',
'Johnstubbs1012@gmail.com',
'j.palethorpe@icloud.com',
'laurahere7@yahoo.co.uk',
'allison1703@gmail.com',
'e_a_walsh_97@hotmail.com',
'Perfect_beat01@hotmail.com',
'andy.web@virgin.net',
'jennyamccallum@hotmail.com',
'rhi_davies_85@hotmail.com',
'peartandrew@yahoo.com',
'oliver.james.allen@hotmail.com',
'swakeman@mac.com',
'invictauk@btconnect.com',
'Beccakmarsden@gmail.com')
group by u.id,
         u.email,
         su.external_id,
         addr.postcode) mmh
on e.email = mmh.email
order by e.id;
-- order by e.email
-- where e.email in (
-- 'pendredsigns@gmail.com',
-- 'emilycharlotte11@gmail.com',
-- 'amit.bhute@gmail.com',
-- 'martinstiksel@gmail.com',
-- 'mrusselljones@gmail.com',
-- 'gail.blackman@me.com',
-- 'georginov@yahoo.com',
-- 'clairerogers77@gmail.com',
-- 'boho1212@gmail.com',
-- 'traceywong@hotmail.co.uk'
-- )
-- group by e.email
-- having count(*)>1
;

select count(*) from temp_email;

drop table temp_email;

create table temp_email
(
  id  bigint,
  email varchar(500)
);

insert into temp_email
values (1,'Ozxavi@gmail.com'),
(2,'tara.mann@me.com'),
(3,'mark.wreford@gmail.com'),
(4,'robertjsills@yahoo.co.uk'),
(5,'rlduffy@dsl.pipex.com'),
(6,'fazenumber4@yahoo.co.uk'),
(7,'Matthewleigh23@outlook.com'),
(8,'wesley.bleach@hotmail.co.uk'),
(9,'cindysharman@gmail.com'),
(10,'lochlan.macdonald@cityofglondon.gov.uk'),
(11,'derek13hearne@gmail.com'),
(12,'chawkesm@gmail.com'),
(13,'esmejaye1@gmail.com'),
(14,'sminamioka@gmail.com'),
(15,'steven@room14.co.uk'),
(16,'Harry.woodington@gmail.com'),
(17,'andrewrclark90@gmail.com'),
(18,'peeldamian@mac.com'),
(19,'Davydward@yahoo.co.uk'),
(20,'Karinhanna@sky.com'),
(21,'jimpage@me.com'),
(22,'mariamahon27@yahoo.com'),
(23,'oneadr@yahoo.co.uk'),
(24,'ewanmcintosh@Sky.com'),
(25,'utilities@de-borde.co.uk'),
(26,'carmantrathen@icloud.com'),
(27,'mockingbird11@virginmedia.com'),
(28,'jdp@liverpool.ac.uk'),
(29,'djhistory@gmail.com'),
(30,'neil@mellerick.co.uk'),
(31,'aaron.warren@howardhunt.com'),
(32,'geraldsheehan5@gmail.com'),
(33,'chris.sheppard@yahoo.com'),
(34,'petergibson@iname.com'),
(35,'Fiser@me.com'),
(36,'neil.edwards567@gmail.com'),
(37,'Leahalice156@gmail.com'),
(38,'Alynicholson@aol.com'),
(39,'michael_streets@yahoo.com'),
(40,'david.pert@sky.com'),
(41,'dan_si_vio@yahoo.com'),
(42,'jamescave@outlook.com'),
(43,'suzy.wuzy@hotmail.co.uk'),
(44,'philipdavidge@gmail.com'),
(45,'ziyakhan@hotmail.com'),
(46,'Markscott.ee@gmail.com'),
(47,'rob.isitt@hotmail.co.uk'),
(48,'jonathanphilpotts@me.com'),
(49,'gillen_j@hotmail.com'),
(50,'mark@kelmhouse.co.uk'),
(51,'jeankruger64@gmail.com'),
(52,'amcdon41177@aol.com'),
(53,'toneoldbone@gmail.com'),
(54,'david_wetton@yahoo.com'),
(55,'rickygilb@btinternet.com'),
(56,'Nicola.christian@hotmail.co.uk'),
(57,'garry@heatcare.com'),
(58,'gjholland125@gmail.com'),
(59,'henrypugh82@gmail.com'),
(60,'cazza_sanderson@yahoo.co.uk'),
(61,'dawn.chatwin@sky.com'),
(62,'colinandrews600@gmail.com'),
(63,'neilfox@gmail.com'),
(64,'olly@thinkmovechange.com'),
(65,'david.mcdonnell@btinternet.com'),
(66,'Juliajb@hotmail.co.uk'),
(67,'geoffgoff@virginmedia.com'),
(68,'rebecca_adams_87@hotmail.co.uk'),
(69,'James.ramsden@gmail.com'),
(70,'skulla_funga@hotmail.com'),
(71,'paulchandler23@gmail.com'),
(72,'nick@theschroeders.co.uk'),
(73,'lcshiels@gmail.com'),
(74,'theresamac32@gmail.com'),
(75,'duncan.banks@open.ac.uk'),
(76,'Peter.mackenzie@ntlworld.com'),
(77,'bazsyd@hotmail.com'),
(78,'markcharles1980@gmail.com'),
(79,'mlawrence13130@gmail.com'),
(80,'victorialewin@hotmail.co.uk'),
(81,'itlane@outlook.com'),
(82,'contact@spiky.fr'),
(83,'lyndsay_mcnicol@hotmail.com'),
(84,'18094'),
(85,'me@seanharrison.co.uk'),
(86,'amit.bhute@gmail.com'),
(87,'sammi_jo86@hotmail.com'),
(88,'katie.osborne89@yahoo.com'),
(89,'nick@nickwarren.net'),
(90,'janice.mahoney@allianz.co.uk'),
(91,'lidbert@ntlworld.com'),
(92,'chris.bradbury@gmail.com'),
(93,'punchard@les-gaz.net'),
(94,'dickonroberts@gmail.com'),
(95,'gail.blackman@me.com'),
(96,'liz.hewitt2012@btinternet.com'),
(97,'zoe.sorotos@gmail.com'),
(98,'dave.stejonda@gmail.com'),
(99,'offduty@orchard21.plus.com'),
(100,'barbara@polglaze.plus.com'),
(101,'richard_brazier@hotmail.com'),
(102,'s.jmilligan@sky.comans.j'),
(103,'patrickdunne@yahoo.com'),
(104,'jandahole@gmail.com'),
(105,'kitchong@hotmail.co.uk'),
(106,'ken@keggie.com'),
(107,'redmen1963@gmail.com'),
(108,'denniswhitelondon@gmail.com'),
(109,'carolejohnson@ymail.com'),
(110,'Energy@kitchenfitter.co.uk'),
(111,'blossevans@yahoo.co.uk'),
(112,'kaz529@aol.com'),
(113,'mistermallet@hotmail.com'),
(114,'p.whitneypdr@gmail.com'),
(115,'hj-oldiesinthesticks@uwclub.net'),
(116,'rke925@yahoo.co.uk'),
(117,'pendredsigns@gmail.com'),
(118,'deharding1@btinternet.com'),
(119,'allen.playford@btinternet.com'),
(120,'kieroncreagh@outlook.com'),
(121,'ian_t_smart@hotmail.com'),
(122,'duncanwesterman@talktalk.net'),
(123,'Ianpotter160@btinternet.com'),
(124,'pauljesmith33@gmail.com'),
(125,'Sarahddykes@gmail.com'),
(126,'k.harcourtsmith@btinternet.com'),
(127,'normarees49@hotmail.co.uk'),
(128,'dommatthews@gmail.com'),
(129,'Rhianlbaker@gmail.com'),
(130,'jsnoon@virginmedia.com'),
(131,'pkm321@live.co.uk'),
(132,'peter.anderson@Adelphigroup.com'),
(133,'Christophermorgan1@sky.com'),
(134,'nickyluff@icloud.com'),
(135,'emmanuel.lebecq@me.com'),
(136,'joyma@hushmail.com'),
(137,'mrotuhey@gmail.com'),
(138,'Suzanne.white97@ntlworld.com'),
(139,'jamie_cooper@btinternet.com'),
(140,'scott@scotthunt.co.uk'),
(141,'adealtry50@gmail.com'),
(142,'maskilljohn@yahoo.co.uk'),
(143,'Gemmahowell66@yahoo.co.uk'),
(144,'suehooper323@btinternet.com'),
(145,'29339 graham.stephenson2014@gmail.com'),
(146,'sdcarroll849@btinternet.com'),
(147,'andreactownend@sky.com'),
(148,'sandpbushnell@gmail.com'),
(149,'tcb.beb@btinternet.com'),
(150,'rogers.harry@gmail.com'),
(151,'Craig.tanner@icloud.com'),
(152,'thehooks8@gmail.com'),
(153,'daniel.m.williams@hotmail.com'),
(154,'jam.jar@sky.com'),
(155,'ian6hurst@gmail.com'),
(156,'mogue2@hotmail.co.uk'),
(157,'Michaelrowden@hotmail.co.uk'),
(158,'jdgriffiths608@hotmail.com'),
(159,'zhaninam@gmail.com'),
(160,'Mooreaneta200@gmail.com'),
(161,'eltonvaughan@gmail.com'),
(162,'200006740@btconnect.com'),
(163,'nickhollisuk@yahoo.co.uk'),
(164,'gary.barnes1@btinternet.com'),
(165,'Jeng871@btinternet.com'),
(166,'n.matthews-graves@hotmail.co.uk'),
(167,'steve.h.partridge@ntlworld.com'),
(168,'karen.way1@ntlworld.com'),
(169,'STEVE@RAVENESQUE.CO.UK'),
(170,'athertp@yahoo.co.uk'),
(171,'juliestrong@btinternet.com'),
(172,'David109lawrence@gmail.com'),
(173,'garybollands@gmail.com'),
(174,'jimbirdzz@netscape.net'),
(175,'sarahlynnette55@yahoo.co.uk'),
(176,'Karl.halliday35@gmail.com'),
(177,'paul@paultelco.com'),
(178,'thomas.white2772@gmail.com'),
(179,'cransom61@hotmail.com'),
(180,'nsweitz@gmail.com'),
(181,'jbsquared@btinternet.com'),
(182,'a.jtorquay@gmail.com'),
(183,'dilysaudrey8@gmail.com'),
(184,'noncore@corlessfamily.com'),
(185,'tonyhand123@btinterne.tcom'),
(186,'junethackrah@me.com'),
(187,'Rdrayton210@gmail.com'),
(188,'isallt.nantlle@gmail.com'),
(189,'Pragnaa@aol.com'),
(190,'philbuck83@hotmail.co.uk'),
(191,'kevin@vivvid.co.uk'),
(192,'dannmacuk@aol.com'),
(193,'chrs.holland@gmail.com'),
(194,'terrycrone@hotmail.com'),
(195,'jhnaismith@gmail.com'),
(196,'graley@gainsoft.co.uk'),
(197,'sarah.whitehouse@6kbw.com'),
(198,'sarboykay@hotmail.com'),
(199,'richardsonmichael242@gmail.com'),
(200,'brianr77@blueyonder.co.uk'),
(201,'alheard79@gmail.com'),
(202,'johnanstiss@hotmail.com'),
(203,'elaine.sharp84@gmail.com'),
(204,'jamie.kind26@gmail.com'),
(205,'Thistledoo1@gmail.com'),
(206,'ruthpitt12@gmail.com'),
(207,'dlmajor@sky.com'),
(208,'bairey89@gmail.com'),
(209,'caroleiw@yahoo.com'),
(210,'juliawhiting24@icloud.com'),
(211,'gpiazzon@hotmail.co.uk'),
(212,'32626 jonathansoper@hotmail.com'),
(213,'nienawidzetuska@gmail.com'),
(214,'cmbc.stengel@gmail.com'),
(215,'djhspooner@gmail.com'),
(216,'marcel.vanheijzen@yahoo.co.uk'),
(217,'gillkf@gmail.com'),
(218,'martinstiksel@gmail.com'),
(219,'zchrislongman@hotmail.com'),
(220,'kennyjhowse@gmail.com'),
(221,'Smudge9446@gmail.com'),
(222,'ma.kaulics@gmail.com'),
(223,'traceywong@hotmail.co.uk'),
(224,'Margaret.tabbener@gmail.com077658'),
(225,'Chasfyoung@googlemail.com'),
(226,'marcus.swalwell@gmail.com'),
(227,'joanna.gallimore@yahoo.com'),
(228,'ash.hansla@outlook.com'),
(229,'ashley_rossington@hotmail.com'),
(230,'debbietear70@gmail.com'),
(231,'jconnick@msn.com'),
(232,'jason.jutla@gmail.com'),
(233,'Angiehael@googlemail.com'),
(234,'June@juneburrough.co.uk'),
(235,'neilshouse@gmail.com'),
(236,'chad.h.saunders+mse@gmail.com'),
(237,'richardandabbie@gmail.com'),
(238,'briggselectrical@yahoo.co.uk'),
(239,'richard.windred@btinternet.com'),
(240,'crdia801@aol.com'),
(241,'jalavender@practicalactions.co.uk'),
(242,'Kellyboy69@sky.com'),
(243,'jonayling@gmail.com'),
(244,'tofugeek@gmail.com'),
(245,'1967kevin@gmail.com'),
(246,'tony.pagett@blueyonder.co.uk'),
(247,'basicexposure@icloud.com'),
(248,'Ian_parfitt@hotmail.co.uk'),
(249,'b.turner93@ntlworld.com'),
(250,'juwil.symington@gmail.com'),
(251,'lyn.e.crawford@gmail.com'),
(252,'mechapman@blueyonder.co.uk'),
(253,'gillandpearson@hotmail.com'),
(254,'dentpatrick@hotmail.com'),
(255,'plumtreec@gmail.com'),
(256,'adrian.wigham@yahoo.co.uk'),
(257,'carlymw253@gmail.com'),
(258,'brian.baker15@btinternet.com'),
(259,'rmh@holdom.net'),
(260,'alvie.mahmud@hotmail.co.uk'),
(261,'si.willcox@gmail.com'),
(262,'c.callanan@homecall.co.uk'),
(263,'rod.grinsted2@gmail.com'),
(264,'carolynmccann@gmail.com'),
(265,'tompop01@madasafish.com'),
(266,'nivek.retsel@gmail.com'),
(267,'jasonnicki5@hotmail.com'),
(268,'lloydmartyn@hotmail.com'),
(269,'Clark465@btinternet.com'),
(270,'32920 mayporter300@gmail .com'),
(271,'Paulrowlie@gmail.com'),
(272,'dltc.davidlane@gmail.com'),
(273,'benedict.mcguigan@gmail.com'),
(274,'ruthclemiw@hotmail.com'),
(275,'tonecat101@outlook.com'),
(276,'jmtaylor948@gmail.com'),
(277,'vstokeley@hotmail.com'),
(278,'alistair@burmark.co.uk'),
(279,'gilly_taylor21@hotmail.co.uk'),
(280,'tonester666@gmail.com'),
(281,'sharon.wilson@hotmail.com'),
(282,'hayley@littleun.com'),
(283,'jon@setty.co.uk'),
(284,'ccbam83@gmail.com'),
(285,'m.cartledge@sky.com'),
(286,'Beckywrigley@icloud.com'),
(287,'rachelembleton75@gmail.com'),
(288,'garyorton71@gmail.com'),
(289,'roughlini@icloud.com'),
(290,'jwdigby@hotmail.com'),
(291,'peterhs@doctors.org.uk'),
(292,'Ljcspencer@hotmail.co.uk'),
(293,'shell_1_@hotmail.com'),
(294,'Lexdev@icloud.com'),
(295,'Mary-annriley@hotmail.com'),
(296,'gagvasquez@gmail.com'),
(297,'neil@atkinson.name'),
(298,'ezragarcia91@zoho.com'),
(299,'streamfraser@btinternet.com'),
(300,'Mail@joeellis.co.uk'),
(301,'lucilla@blueyonder.co.uk'),
(302,'westfield.am@googlemail.com'),
(303,'maidment123@icloud.com'),
(304,'meintrow@hotmail.co.uk'),
(305,'graham1946@hotmail.co.uk'),
(306,'vbansal@live.co.uk'),
(307,'r.kasher@sky.com'),
(308,'Beverleyfarnish@icloud.com'),
(309,'christopherjamesbircham@gmail.com'),
(310,'tomgareh@hotmail.com'),
(311,'davetarr1@gmail.com'),
(312,'junepenfold@gmail.com'),
(313,'matabolix@hotmail.com'),
(314,'martingillpost@gmail.com'),
(315,'donrogers@sky.com'),
(316,'donna.brindle@sky.com'),
(317,'david.madle@ricardo.com'),
(318,'olayinkamosadomi@gmail.com'),
(319,'benskirrow111@gmail.com'),
(320,'lornalalji@gmail.com'),
(321,'yemenmike@aol.com'),
(322,'Luciajoni@hotmail.co.uk'),
(323,'Marctomschofield@hotmail.com'),
(324,'Niki.pearce@live.co.uk'),
(325,'Kaarenremington @hotmail.co.uk'),
(326,'tonyknife1970@googlemail.com'),
(327,'Jillsshines@gmail.com'),
(328,'na_mcdonald@icloud.com'),
(329,'sipuncher@gmail.com'),
(330,'seb_squeak@live.com'),
(331,'burstowr@aol.com'),
(332,'stevebold@blueyonder.co.uk'),
(333,'sueruss.stewart@gmail.com'),
(334,'samedwards2207@gmail.com'),
(335,'igloo@mjbk.uk'),
(336,'mitch.paris@live.co.uk'),
(337,'sharon_alva@yahoo.co.uk'),
(338,'mpagram@icloud.com'),
(339,'mnalista@hotmail.co.uk'),
(340,'peter@peterjagger.co.uk'),
(341,'pauldavidcrouch@gmail.com'),
(342,'s.palmerralph@outlook.com'),
(343,'trevor.may@btinternet.com'),
(344,'aabr05@icloud.com'),
(345,'jkilmister@gmail.com'),
(346,'aamirbc2000@yahoo.com'),
(347,'36667 a.milton@virgin.net'),
(348,'michaelgwatson77@gmail.com'),
(349,'pwd41284@yahoo.co.uk'),
(350,'loshears@gmail.com'),
(351,'zannaw@hotmail.com'),
(352,'rleigh.mail@gmail.com'),
(353,'cduffain@gmail.com'),
(354,'alandeunice@yahoo.com'),
(355,'martyncooper1@sky.com'),
(356,'jack_samways@hotmail.com'),
(357,'keeble269@gmail.com'),
(358,'sallyhalls@gmail.com'),
(359,'6156 kevin@cleasbyonline.co.uk'),
(360,'mrsideshowjack@gmail.com'),
(361,'barrywhlr@gmail.com'),
(362,'kewal.rai75@gmail.com'),
(363,'raymond.booth@gmail.com'),
(364,'allan.battersby@btopenworld.com'),
(365,'kategreeves@hotmail.com'),
(366,'duncangunstone@hotmail.com'),
(367,'dpm661@gmail.com'),
(368,'rupertcapleton@yahoo.com'),
(369,'adedayobenson@yahoo.com'),
(370,'charlotte.burn2012@gmail.com'),
(371,'Kerrypratt96@gmail.com'),
(372,'scottpunton@hotmail.co.uk'),
(373,'pbclarke21@gmail.com'),
(374,'Ben.dingley@hot.co.uk'),
(375,'turnbull.kieran@gmail.com'),
(376,'Gbarrat122@gmailcom'),
(377,'swampington@hotmail.com'),
(378,'boho1212@gmail.com'),
(379,'Matt_whitton4@hotmail.com'),
(380,'a.thompson135@btinternet.com'),
(381,'burts.bike@gmail.com'),
(382,'holbrow.chris@gmail.com'),
(383,'mwhogg74@gmail.com'),
(384,'tony_wilkinson2003@yahoo.co.uk'),
(385,'Rmpooley@gmail.com'),
(386,'mfthomas@lineone.net'),
(387,'midimode@btinternet.com'),
(388,'mnsomersltd@googlemail.com'),
(389,'"Lyndhurst", 8 Mount Vernon Road, Barnsley, South Yorkshire, S70 4DJ.'),
(390,'petardim914@gmail.com'),
(391,'Kristina.gorkovskaya@gmail.com'),
(392,'Gkh416@hotmail.com'),
(393,'anastasia.cunningham@ntlworld.com'),
(394,'jaymereaves@gmail.com'),
(395,'sylwia@nationwideproduce.com'),
(396,'timothymjharper@gmail.com'),
(397,'alistermacnaught@yahoo.com'),
(398,'johnmelrose42@icloud.com'),
(399,'jameslittmann@gmail.com'),
(400,'les_survey@btinternet.com'),
(401,'nirmaank@hotmail.com'),
(402,'williammathieson1@outlook.com'),
(403,'mike1939davis@gmail.com'),
(404,'A/C 35989 cp@cgp.me.uk'),
(405,'ian@beerandcurry.me.uk'),
(406,'colroselloyd@btinternet.com'),
(407,'adrian.gamble@gmx.com'),
(408,'clare.a.hancock@gmail.com'),
(409,'malcolmsaunders@btinternet.com'),
(410,'valerie.hazan@gmail.com'),
(411,'nige.bamford@gmail.com'),
(412,'claudneves@gmail.com'),
(413,'patricia@pattigran.plus.com'),
(414,'c.greenway@ntlworld.com'),
(415,'2775, colin.littler@yahoo.co.uk'),
(416,'peter.ellis70@ntlworld.com'),
(417,'hfagon@gmail.com'),
(418,'paul@rodgerwillco.com'),
(419,'sbillett@gmail.com'),
(420,'mick_hewitt@btconnect.com'),
(421,'mick@donmcmath.org'),
(422,'fry.a@ntlworld.com'),
(423,'weknowwhereyoulive@gmail.com'),
(424,'dustin.lees@outlook.com'),
(425,'carl_stevenson@mac.com'),
(426,'karmanchung@gmail.com'),
(427,'tonymmoore@btinternet.com'),
(428,'elimron10@ntlworld.com'),
(429,'Trlawnm@gmail.com'),
(430,'Samanthaleenders@hotmail.co.uk'),
(431,'davidsables@gmail.com'),
(432,'herwagner@hotmail.com'),
(433,'Janet.nock@gmail.com'),
(434,'malcolmwatson986@yahoo.co'),
(435,'andy.hepworth@hotmail.co.uk'),
(436,'maxim.armour@gmail.com'),
(437,'Liz.gearing@btinternet.com'),
(438,'clairerogers77@gmail.com'),
(439,'edwardbaers@hotmail.co.uk'),
(440,'r1mmels@hotmail.com'),
(441,'Sharonmilner880@gmail.com'),
(442,'Barryandjanewyton@sky.com'),
(443,'terry400@gmail.com'),
(444,'petermarsh68@gmail.com'),
(445,'mikec@homemail.com'),
(446,'crusoesleap@yahoo.co.uk07979741007'),
(447,'natalieholloway@hotmail.co.uk'),
(448,'iammayhew@icloud.com'),
(449,'tony@58lions.co.uk'),
(450,'dave@davegarner.co.uk'),
(451,'robert1960rolls@gmail.com'),
(452,'keenemh@aol.com'),
(453,'bruceduncan158@yahoo.com'),
(454,'hamish.stewart@gmail.com'),
(455,'katherine.zambaldi@gmail.com'),
(456,'srmt@btinternet.com'),
(457,'simonpannett@aol.com'),
(458,'roddy.gilly@gmail.com'),
(459,'ajmalras@gmail.co.uk'),
(460,'peterwilcoxcm@gmail.com'),
(461,'fosworld@hotmail.com'),
(462,'clairenrich@gmail.com'),
(463,'lynandbob@virginmedia.com'),
(464,'alantrotman@hotmail.co.uk'),
(465,'JDChapman2000@GMail.com'),
(466,'robert_j_simmonds@hotmail.co.uk'),
(467,'robsdixon@gmail.com'),
(468,'mandpshopping@btinternet.com'),
(469,'tony@gentone.co.uk'),
(470,'janfrodsham@hotmail.com'),
(471,'osmond266@yahoo.co.uk'),
(472,'Jennfinch@btinternet.com'),
(473,'lasher1539@hotmail.com'),
(474,'hawleyian@btinternet.com'),
(475,'bberry259@gmail.com'),
(476,'mdfleming@virginmedia.com'),
(477,'nishmashah@hotmail.com'),
(478,'andy.kemp1@ntlworld.com'),
(479,'judit.pelikan@gmail.com'),
(480,'jskilly1@aol.com'),
(481,'peterturner@hotmail.com'),
(482,'c.walker@hotmail.co.uk'),
(483,'amccuaig@brightred.com'),
(484,'rujutathegreat@hotmail.com'),
(485,'iangb_2000@yahoo.co.uk'),
(486,'jimonhismobile@gmail.com'),
(487,'geoff_bowron@hotmail.com'),
(488,'witchypoo1949@googlemail.com'),
(489,'Bob_page@talk21.com'),
(490,'yockney@yahoo.com'),
(491,'leprechaun201@hotmail.com'),
(492,'prmaidment@gmail.com'),
(493,'elp79.ep@googlemail.com'),
(494,'milesdj287@googlemail.com'),
(495,'mr@egrouse.com'),
(496,'ppspdh@aol.com'),
(497,'paulevans@postinbox.com'),
(498,'darren-petherick@hotmail.co.uk'),
(499,'vinny59@hotmail.co.uk'),
(500,'davidtmartin@icloud.com'),
(501,'pdl300@hotmail.com'),
(502,'mmarkk_2@hotmail.com'),
(503,'stephenshuttleworth@hotmail.com'),
(504,'annetod@icloud.com'),
(505,'beezle3@yahoo.com'),
(506,'craig.bufton@outlook.com'),
(507,'ajlaing@acplc.net'),
(508,'james84hare@gmail.com'),
(509,'johnlikeman@yahoo.co.uk'),
(510,'irimsarwar@gmail.com'),
(511,'patterson_j2@sky.com'),
(512,'Admiremandaza1@gmail.com'),
(513,'Sswinzy1@gmail.com'),
(514,'Castellanoslorenzo@gmail.com'),
(515,'Scott.motion@live.co.uk'),
(516,'katerina.woolhouse@gmail.com'),
(517,'russellprice@me.com'),
(518,'tomjoshw1997@gmail.com'),
(519,'nicolas.rose@sony.com'),
(520,'w'),
(521,'yxmk551k@gmail.com'),
(522,'pilar.matji95@gmail.com'),
(523,'matt752@hotmail.com'),
(524,'29 Cavendish Drive, TN2 5DU'),
(525,'crippsfarm@gmail.com'),
(526,'Tonyturton@btinternet.com'),
(527,'arben290@gmail.com'),
(528,'hamish_anderson@btinternet.com'),
(529,'37036 avrilcherry@gmail.com'),
(530,'br_marks@hotmail.com'),
(531,'sezam.uk@gmail.com'),
(532,'andy_powles@hotmail.com'),
(533,'georginov@yahoo.com'),
(534,'Jamiewhmltn@gmail.com'),
(535,'graeme.aldridge@gmail.com'),
(536,'thomasparker32@gmx.com'),
(537,'lcg8477@gmail.com'),
(538,'lionel7bell@yahoo.co.uk'),
(539,'Scvddw@yahoo.co.uk'),
(540,'rebecca_hewes@hotmail.com'),
(541,'gemmapidsley@hotmail.co.uk'),
(542,'emilycharlotte11@gmail.com'),
(543,'gareth.lewis@astrazeneca.com'),
(544,'georgejedwards@gmail.com'),
(545,'belindajholley@gmail.com'),
(546,'hss_sidhu@yahoo.co.uk'),
(547,'pete@williamsresidence.co.uk'),
(548,'29607 vixbeale@gmail.com'),
(549,'woodwardtp@gmail.com'),
(550,'M.cumberlidge@btopenworld.com'),
(551,'b.taylor26@sky.com'),
(552,'kazgood39@yahoo.co.uk'),
(553,'dorchestermike@outlook.com'),
(554,'7998 mooneen@aol.com'),
(555,'littlefollies@hotmail.co.uk'),
(556,'colin@martyn-meade.co.uk'),
(557,'robert.jones@standardsbg.com'),
(558,'dhwynne@hotmail.com'),
(559,'Meganfoste@aol.com'),
(560,'unclepete100@gmail.com'),
(561,'alfredshipp65@hotmail.com'),
(562,'youngysk41@gmail.com'),
(563,'jamesmcneice61@hotmail.com'),
(564,'elonagreenaway@btinternet.com'),
(565,'gemmaeade@hotmail.com'),
(566,'blu_tirohl@hotmail.com'),
(567,'Aagoren'),
(568,'lisacstamp@gmail.com'),
(569,'PRAFUL_MAKWANA@HOTMAIL.CO.UK'),
(570,'Davidzim@btinternet.com'),
(571,'kathyb12@hotmail.co.uk'),
(572,'terry.seaber@ntlworld.com'),
(573,'1955.sp@gmail.com'),
(574,'lynne1804@gmail.com'),
(575,'Justin_allenuk@yahoo.co.uk'),
(576,'louis.otway@gmail.com'),
(577,'aussiestew@talk21.com'),
(578,'bblockley1@btinternet.com'),
(579,'kate@mjsmortgages.co.uk'),
(580,'roly.ryan1@outlook.com'),
(581,'nigel.cronin@gmail.com'),
(582,'Keith.heaviside@rocketmail.com'),
(583,'johnm@mitch.uk.com'),
(584,'alexandra.maria2606@gmail.com'),
(585,'anarayandookie@gmail.com'),
(586,'trev101@live.co.uk'),
(587,'Antony.bird@newsprinters.co.uk'),
(588,'annie@anniegriffith.co.uk'),
(589,'Fraserk@virginmedia.com'),
(590,'poppajon43@gmail.com'),
(591,'Mazpez@hotmail.com'),
(592,'uglyson64@gmail.com'),
(593,'gc.brown@ntlworld.com'),
(594,'Everitt-jones@hotmail. Com'),
(595,'robinhard@btinternet.com'),
(596,'joshcarter1998@icloud.com'),
(597,'clairecrudge@btinternet.com'),
(598,'Rick.duffy@outlook.com'),
(599,'tomatr250@gmail.com'),
(600,'sandeep49@yahoo.com'),
(601,'peter.hackman06@gmail.com'),
(602,'paul@meridenlodge.co.uk'),
(603,'jezwhite1@hotmail.com'),
(604,'damanning.manning9@gmail.com'),
(605,'1bobbygibbs@gmail.com'),
(606,'danny@qvs-uk.com'),
(607,'phil.edgell@gmail.com'),
(608,'jeannedarrington@hotmail.com'),
(609,'lizzie_brown@hotmail.com'),
(610,'acmedway42@googlemail.com'),
(611,'Macdoylefamily@gmail.com'),
(612,'francescolog67@gmail.com'),
(613,'hazzer999@gmail.com'),
(614,'p.onions@btinternet.com'),
(615,'chrisrwebber@gmail.com'),
(616,'leigh.bidmead@gmail.com'),
(617,'mandcblackburn@googlemail.com'),
(618,'mike@smalley.biz'),
(619,'mrusselljones@gmail.com'),
(620,'barrettsallyanne@gmail.com'),
(621,'janettebowen@hotmail.com'),
(622,'Paul.0.jones@btinternet.com'),
(623,'drsajenkins@btinternet.com'),
(624,'huangheruby86@gmail.com'),
(625,'Claire.ferrao@gmail.com'),
(626,'andyburlow@gmail.com'),
(627,'Matt.sj.gardner@gmail.com'),
(628,'mjackson2@talktalk.net'),
(629,'ruthylangford@gmail.com'),
(630,'stephenwlord@gmail.com'),
(631,'wiggins.debbie@gmail.com'),
(632,'steve.eade@gmx.com'),
(633,'jacekowski@jacekowski.org'),
(634,'jinobs@gmail.com'),
(635,'Clare.hunter2@ntlworld.com'),
(636,'jjalder@hotmail.com'),
(637,'andy.saxton@icloud.com'),
(638,'steven.hardstaff@ucyfc.co.uk'),
(639,'phgoodwin23@gmail.com'),
(640,'lj.weir@btinternet.com'),
(641,'mikecook@blueyonder.co.uk'),
(642,'sophiestradins@gmail.com'),
(643,'kim.allyson@ntlworld.com'),
(644,'owen!@mdx.ac.uk'),
(645,'FJBowers@msn.com'),
(646,'thejanx@live.co.uk'),
(647,'Johnstubbs1012@gmail.com'),
(648,'j.palethorpe@icloud.com'),
(649,'laurahere7@yahoo.co.uk'),
(650,'allison1703@gmail.com'),
(651,'e_a_walsh_97@hotmail.com'),
(652,'Perfect_beat01@hotmail.com'),
(653,'andy.web@virgin.net'),
(654,'jennyamccallum@hotmail.com'),
(655,'rhi_davies_85@hotmail.com'),
(656,'peartandrew@yahoo.com'),
(657,'oliver.james.allen@hotmail.com'),
(658,'swakeman@mac.com'),
(659,'invictauk@btconnect.com'),
(660,'Beccakmarsden@gmail.com')
;

delete from temp_email;
