select account_id,
       igloo_user_id,
       registration_id,
       registration_uprn,
       account_status,
       meterpoint_type_elec,
       meterpoint_type_gas,
       dual,
       meterpoints_status_elec,
       meterpoints_status_gas,
       supply_startdate_elec,
       supply_enddate_elec,
       supply_startdate_gas,
       supply_enddate_gas,
       num_bedrooms,
       num_adults,
       heating_type,
       postcode,
    --EPC
       current_energy_rating,
       potential_energy_rating,
       current_energy_efficiency,
       potential_energy_efficiency,
       property_type_epc,
       built_form,
       inspection_date,
       local_authority,
       constituency,
       county,
       lodgement_date,
       transaction_type,
       environment_impact_current,
       environment_impact_potential,
       energy_consumption_current,
       energy_consumption_potential,
       co2_emissions_current,
       co2_emiss_curr_per_floor_area,
       co2_emissions_potential,
       lighting_cost_current,
       lighting_cost_potential,
       heating_cost_current,
       heating_cost_potential,
       hot_water_cost_current,
       hot_water_cost_potential,
       total_floor_area,
       energy_tariff,
       mains_gas_flag,
       floor_level,
       flat_top_storey,
       flat_storey_count,
       main_heating_controls,
       multi_glaze_proportion,
       glazed_type,
       glazed_area,
       extension_count,
       number_habitable_rooms,
       number_heated_rooms,
       low_energy_lighting,
       number_open_fireplaces,
       hotwater_description,
       hot_water_energy_eff,
       hot_water_env_eff,
       floor_description,
       floor_energy_eff,
       floor_env_eff,
       windows_description,
       windows_energy_eff,
       windows_env_eff,
       walls_description,
       walls_energy_eff,
       walls_env_eff,
       secondheat_description,
       sheating_energy_eff,
       sheating_env_eff,
       roof_description,
       roof_energy_eff,
       roof_env_eff,
       mainheat_description,
       mainheat_energy_eff,
       mainheat_env_eff,
       mainheatcont_description,
       mainheatc_energy_eff,
       mainheatc_env_eff,
       lighting_description,
       lighting_energy_eff,
       lighting_env_eff,
       main_fuel,
       wind_turbine_count,
       heat_loss_corridoor,
       unheated_corridor_length,
       floor_height,
       photo_supply,
       solar_water_heating_flag,
       mechanical_ventilation,
    -- Epc Recommendations
       improvement_descr_text,
       improvement_id,
       improvement_id_text,
       improvement_item,
       improvement_summary_text,
    --Land Registry
       transaction_date,
       new_build,
       price_paid,
       property_type_land_registry,
       record_status,
       transaction_category,
    -- ref_calculate_eac_aq
       register_id          as register_id_eac,
       industry_eac         as register_industry_eac,
       igloo_eac            as register_annualised_eac,
       register_id          as register_id_aq,
       industry_aq          as register_industry_aq,
       igloo_aq             as register_annualised_aq,
    --Non-Fixed MMH
       user_id,
       dhw_tank_present,
       heating_control,
       heating_extent,
       number_of_bedrooms,
       number_of_occupants,
       heating_age,
       dwelling_age,
       heating_setpoint,
       main_heat_source,
       dwelling_type,
       a_dishwasher_age,
       a_dishwasher_owned,
       a_dishwasher_use,
       a_power_shower_age,
       a_power_shower_owned,
       a_power_shower_use,
       a_tumble_dryer_age,
       a_tumble_dryer_owned,
       a_tumble_dryer_use,
       a_washer_dryer_age,
       a_washer_dryer_owned,
       a_washer_dryer_use,
       a_washing_machine_age,
       a_washing_machine_owned,
       a_washing_machine_use,
       ka_electric_hob_age,
       ka_electric_hob_owned,
       ka_electric_hob_use,
       ka_electric_oven_age,
       ka_electric_oven_owned,
       ka_electric_oven_use,
       ka_fridge_freezer_age,
       ka_fridge_freezer_owned,
       ka_fridge_freezer_use,
       ka_gas_hob_age,
       ka_gas_hob_owned,
       ka_gas_hob_use,
       ka_gas_oven_age,
       ka_gas_oven_owned,
       ka_gas_oven_use,
       ka_standalone_freezer_age,
       ka_standalone_freezer_owned,
       ka_standalone_freezer_use,
       ka_standalone_fridge_age,
       ka_standalone_fridge_owned,
       ka_standalone_fridge_use,
       person_10_age,
       person_11_age,
       person_12_age,
       person_13_age,
       person_14_age,
       person_15_age,
       person_16_age,
       person_17_age,
       person_18_age,
       person_19_age,
       person_1_age,
       person_20_age,
       person_21_age,
       person_22_age,
       person_23_age,
       person_24_age,
       person_2_age,
       person_3_age,
       person_4_age,
       person_5_age,
       person_6_age,
       person_7_age,
       person_8_age,
       person_9_age
from (select su.external_id           as account_id,
       rcup.user_id             as igloo_user_id,
       reg.id                   as registration_id,
       rca.uprn                 as registration_uprn,
       ac.status                as account_status,
       vmp_elec.meterpointtype  as meterpoint_type_elec,
       vmp_gas.meterpointtype   as meterpoint_type_gas,
       case
         when (vmp_elec.meterpointtype is not null and vmp_gas.meterpointtype is not null)
                 then 'dual_fuel'
         else 'single_fuel' end as dual,
       case
         when (mp_elec.supplyenddate is null or mp_elec.supplyenddate >= current_date) then 'Live'
         else 'Not Live' end    as meterpoints_status_elec,
       case
         when (vmp_gas.meterpointtype = 'G' and
               (mp_gas.supplyenddate is null or mp_gas.supplyenddate >= current_date)) then 'Live'
         else 'Not Live' end    as meterpoints_status_gas,
       mp_elec.supplystartdate  as supply_startdate_elec,
       mp_elec.supplyenddate    as supply_enddate_elec,
       mp_gas.supplystartdate   as supply_startdate_gas,
       mp_gas.supplyenddate     as supply_enddate_gas,
       qu.num_bedrooms,
       qu.num_adults,
       qu.heating_type,
       rca.postcode             as postcode,
    --EPC
       epc.current_energy_rating,
       epc.potential_energy_rating,
       epc.current_energy_efficiency,
       epc.potential_energy_efficiency,
       epc.property_type as property_type_epc,
       epc.built_form,
       epc.inspection_date,
       epc.local_authority,
       epc.constituency,
       epc.county,
       epc.lodgement_date,
       epc.transaction_type,
       epc.environment_impact_current,
       epc.environment_impact_potential,
       epc.energy_consumption_current,
       epc.energy_consumption_potential,
       epc.co2_emissions_current,
       epc.co2_emiss_curr_per_floor_area,
       epc.co2_emissions_potential,
       epc.lighting_cost_current,
       epc.lighting_cost_potential,
       epc.heating_cost_current,
       epc.heating_cost_potential,
       epc.hot_water_cost_current,
       epc.hot_water_cost_potential,
       epc.total_floor_area,
       epc.energy_tariff,
       epc.mains_gas_flag,
       epc.floor_level,
       epc.flat_top_storey,
       epc.flat_storey_count,
       epc.main_heating_controls,
       epc.multi_glaze_proportion,
       epc.glazed_type,
       epc.glazed_area,
       epc.extension_count,
       epc.number_habitable_rooms,
       epc.number_heated_rooms,
       epc.low_energy_lighting,
       epc.number_open_fireplaces,
       epc.hotwater_description,
       epc.hot_water_energy_eff,
       epc.hot_water_env_eff,
       epc.floor_description,
       epc.floor_energy_eff,
       epc.floor_env_eff,
       epc.windows_description,
       epc.windows_energy_eff,
       epc.windows_env_eff,
       epc.walls_description,
       epc.walls_energy_eff,
       epc.walls_env_eff,
       epc.secondheat_description,
       epc.sheating_energy_eff,
       epc.sheating_env_eff,
       epc.roof_description,
       epc.roof_energy_eff,
       epc.roof_env_eff,
       epc.mainheat_description,
       epc.mainheat_energy_eff,
       epc.mainheat_env_eff,
       epc.mainheatcont_description,
       epc.mainheatc_energy_eff,
       epc.mainheatc_env_eff,
       epc.lighting_description,
       epc.lighting_energy_eff,
       epc.lighting_env_eff,
       epc.main_fuel,
       epc.wind_turbine_count,
       epc.heat_loss_corridoor,
       epc.unheated_corridor_length,
       epc.floor_height,
       epc.photo_supply,
       epc.solar_water_heating_flag,
       epc.mechanical_ventilation,
    -- Epc Recommendations
       sepr.improvement_descr_text,
       sepr.improvement_id,
       sepr.improvement_id_text,
       sepr.improvement_item,
       sepr.improvement_summary_text,
    --Land Registry
       rlr.transaction_date,
       rlr.new_build,
       rlr.price_paid,
       rlr.property_type as property_type_land_registry,
       rlr.record_status,
       rlr.transaction_category,
    -- ref_calculate_eac_aq
       rce.register_id          as register_id_eac,
       rce.industry_eac         as register_industry_eac,
       rce.igloo_eac            as register_annualised_eac,
       rcg.register_id          as register_id_aq,
       rcg.industry_aq          as register_industry_aq,
       rcg.igloo_aq             as register_annualised_aq,
    --Non-Fixed MMH
       tmmhnf.user_id,
       tmmhnf.dhw_tank_present,
       tmmhnf.heating_control,
       tmmhnf.heating_extent,
       tmmhnf.number_of_bedrooms,
       tmmhnf.number_of_occupants,
       tmmhnf.heating_age,
       tmmhnf.dwelling_age,
       tmmhnf.heating_setpoint,
       tmmhnf.main_heat_source,
       tmmhnf.dwelling_type,
       tmmhnf.a_dishwasher_age,
       tmmhnf.a_dishwasher_owned,
       tmmhnf.a_dishwasher_use,
       tmmhnf.a_power_shower_age,
       tmmhnf.a_power_shower_owned,
       tmmhnf.a_power_shower_use,
       tmmhnf.a_tumble_dryer_age,
       tmmhnf.a_tumble_dryer_owned,
       tmmhnf.a_tumble_dryer_use,
       tmmhnf.a_washer_dryer_age,
       tmmhnf.a_washer_dryer_owned,
       tmmhnf.a_washer_dryer_use,
       tmmhnf.a_washing_machine_age,
       tmmhnf.a_washing_machine_owned,
       tmmhnf.a_washing_machine_use,
       tmmhnf.ka_electric_hob_age,
       tmmhnf.ka_electric_hob_owned,
       tmmhnf.ka_electric_hob_use,
       tmmhnf.ka_electric_oven_age,
       tmmhnf.ka_electric_oven_owned,
       tmmhnf.ka_electric_oven_use,
       tmmhnf.ka_fridge_freezer_age,
       tmmhnf.ka_fridge_freezer_owned,
       tmmhnf.ka_fridge_freezer_use,
       tmmhnf.ka_gas_hob_age,
       tmmhnf.ka_gas_hob_owned,
       tmmhnf.ka_gas_hob_use,
       tmmhnf.ka_gas_oven_age,
       tmmhnf.ka_gas_oven_owned,
       tmmhnf.ka_gas_oven_use,
       tmmhnf.ka_standalone_freezer_age,
       tmmhnf.ka_standalone_freezer_owned,
       tmmhnf.ka_standalone_freezer_use,
       tmmhnf.ka_standalone_fridge_age,
       tmmhnf.ka_standalone_fridge_owned,
       tmmhnf.ka_standalone_fridge_use,
       tmmhnf.person_10_age,
       tmmhnf.person_11_age,
       tmmhnf.person_12_age,
       tmmhnf.person_13_age,
       tmmhnf.person_14_age,
       tmmhnf.person_15_age,
       tmmhnf.person_16_age,
       tmmhnf.person_17_age,
       tmmhnf.person_18_age,
       tmmhnf.person_19_age,
       tmmhnf.person_1_age,
       tmmhnf.person_20_age,
       tmmhnf.person_21_age,
       tmmhnf.person_22_age,
       tmmhnf.person_23_age,
       tmmhnf.person_24_age,
       tmmhnf.person_2_age,
       tmmhnf.person_3_age,
       tmmhnf.person_4_age,
       tmmhnf.person_5_age,
       tmmhnf.person_6_age,
       tmmhnf.person_7_age,
       tmmhnf.person_8_age,
       tmmhnf.person_9_age

from ref_cdb_supply_contracts su
       inner join ref_cdb_user_permissions rcup on su.id = rcup.permissionable_id and permission_level = 0 and
                                                   permissionable_type = 'App\\SupplyContract'
       inner join ref_cdb_users rcu on rcup.user_id = rcu.id
       left outer join ref_account_status ac on ac.account_id = su.external_id
       left outer join vw_meterpoint_status_elec vmp_elec on vmp_elec.account_id = su.external_id
       left outer join vw_meterpoint_status_gas vmp_gas on vmp_gas.account_id = su.external_id
       left outer join ref_meterpoints mp_elec
         on mp_elec.account_id = vmp_elec.account_id and mp_elec.meterpointtype = 'E' and
            (mp_elec.supplyenddate < getdate() or mp_elec.supplyenddate is null)
       left outer join ref_meterpoints_attributes rma_gsp
         on mp_elec.meter_point_id = rma_gsp.meter_point_id and rma_gsp.attributes_attributename = 'GSP'
       left outer join ref_meterpoints mp_gas on mp_gas.account_id = vmp_gas.account_id and mp_gas.meterpointtype = 'G'
       left outer join ref_meterpoints_attributes rma_ldz
         on mp_gas.meter_point_id = rma_ldz.meter_point_id and rma_ldz.attributes_attributename = 'LDZ'
       left outer join ref_cdb_addresses rca on su.supply_address_id = rca.id
       left outer join ref_epc_certificates epc on rca.postcode = REPLACE(epc.postcode, ' ', '') and
                                                   public.epcaddressmapping(sub_building_name_number,
                                                                            building_name_number, thoroughfare,
                                                                            dependent_locality) =
                                                   trim(lower(replace(replace(epc.address, '- ', ' '), '-', ' ')))
       left outer join aws_s3_stage2_extracts.stage2_epcrecommendations sepr on epc.lmk_key = sepr.lmk_key
       left outer join ref_land_registry rlr on rca.id = rlr.id
       left outer join ref_cdb_registrations reg on su.registration_id = reg.id
       left outer join ref_cdb_quotes qu on reg.quote_id = qu.id
       left outer join ref_calculated_eac rce on su.external_id = rce.account_id
       left outer join ref_calculated_aq rcg on su.external_id = rcg.account_id
     --  left outer join temp_me_and_my_home_fixed tmmhf on rcup.user_id = tmmhf.user_id
       left outer join aws_s3_stage2_extracts.temp_mmh_non_fixed_answers tmmhnf on rcup.user_id = tmmhnf.user_id
where su.external_id is not null
  and ac.status = 'Live'
group by su.external_id,
         rcup.user_id,
         reg.id,
         rca.uprn,
         ac.status,
         vmp_elec.meterpointtype,
         vmp_gas.meterpointtype,
         case
           when (vmp_elec.meterpointtype is not null and vmp_gas.meterpointtype is not null)
                   then 'dual_fuel'
           else 'single_fuel' end,
         case
           when (mp_elec.supplyenddate is null or mp_elec.supplyenddate >= current_date) then 'Live'
           else 'Not Live' end,
         case
           when (vmp_gas.meterpointtype = 'G' and
                 (mp_gas.supplyenddate is null or mp_gas.supplyenddate >= current_date)) then 'Live'
           else 'Not Live' end,
         mp_elec.supplystartdate,
         mp_elec.supplyenddate,
         mp_gas.supplystartdate,
         mp_gas.supplyenddate,
--Quotes Extract
         qu.num_bedrooms,
         qu.num_adults,
         qu.heating_type,
         rca.postcode,
--EPC Certificates
         epc.current_energy_rating,
         epc.potential_energy_rating,
         epc.current_energy_efficiency,
         epc.potential_energy_efficiency,
         epc.property_type,
         epc.built_form,
         epc.inspection_date,
         epc.local_authority,
         epc.constituency,
         epc.county,
         epc.lodgement_date,
         epc.transaction_type,
         epc.environment_impact_current,
         epc.environment_impact_potential,
         epc.energy_consumption_current,
         epc.energy_consumption_potential,
         epc.co2_emissions_current,
         epc.co2_emiss_curr_per_floor_area,
         epc.co2_emissions_potential,
         epc.lighting_cost_current,
         epc.lighting_cost_potential,
         epc.heating_cost_current,
         epc.heating_cost_potential,
         epc.hot_water_cost_current,
         epc.hot_water_cost_potential,
         epc.total_floor_area,
         epc.energy_tariff,
         epc.mains_gas_flag,
         epc.floor_level,
         epc.flat_top_storey,
         epc.flat_storey_count,
         epc.main_heating_controls,
         epc.multi_glaze_proportion,
         epc.glazed_type,
         epc.glazed_area,
         epc.extension_count,
         epc.number_habitable_rooms,
         epc.number_heated_rooms,
         epc.low_energy_lighting,
         epc.number_open_fireplaces,
         epc.hotwater_description,
         epc.hot_water_energy_eff,
         epc.hot_water_env_eff,
         epc.floor_description,
         epc.floor_energy_eff,
         epc.floor_env_eff,
         epc.windows_description,
         epc.windows_energy_eff,
         epc.windows_env_eff,
         epc.walls_description,
         epc.walls_energy_eff,
         epc.walls_env_eff,
         epc.secondheat_description,
         epc.sheating_energy_eff,
         epc.sheating_env_eff,
         epc.roof_description,
         epc.roof_energy_eff,
         epc.roof_env_eff,
         epc.mainheat_description,
         epc.mainheat_energy_eff,
         epc.mainheat_env_eff,
         epc.mainheatcont_description,
         epc.mainheatc_energy_eff,
         epc.mainheatc_env_eff,
         epc.lighting_description,
         epc.lighting_energy_eff,
         epc.lighting_env_eff,
         epc.main_fuel,
         epc.wind_turbine_count,
         epc.heat_loss_corridoor,
         epc.unheated_corridor_length,
         epc.floor_height,
         epc.photo_supply,
         epc.solar_water_heating_flag,
         epc.mechanical_ventilation,
-- Epc Recommendations
         sepr.improvement_descr_text,
         sepr.improvement_id,
         sepr.improvement_id_text,
         sepr.improvement_item,
         sepr.improvement_summary_text,
--Land Registry
         rlr.transaction_date,
         rlr.new_build,
         rlr.price_paid,
         rlr.property_type,
         rlr.record_status,
         rlr.transaction_category,
-- ref_calculate_eac_aq
         rce.register_id,
         rce.industry_eac,
         rce.igloo_eac,
         rcg.register_id,
         rcg.industry_aq,
         rcg.igloo_aq,
    --Non-Fixed MMH
         tmmhnf.user_id,
         tmmhnf.dhw_tank_present,
         tmmhnf.heating_control,
         tmmhnf.heating_extent,
         tmmhnf.number_of_bedrooms,
         tmmhnf.number_of_occupants,
         tmmhnf.heating_age,
         tmmhnf.dwelling_age,
         tmmhnf.heating_setpoint,
         tmmhnf.main_heat_source,
         tmmhnf.dwelling_type,
         tmmhnf.a_dishwasher_age,
         tmmhnf.a_dishwasher_owned,
         tmmhnf.a_dishwasher_use,
         tmmhnf.a_power_shower_age,
         tmmhnf.a_power_shower_owned,
         tmmhnf.a_power_shower_use,
         tmmhnf.a_tumble_dryer_age,
         tmmhnf.a_tumble_dryer_owned,
         tmmhnf.a_tumble_dryer_use,
         tmmhnf.a_washer_dryer_age,
         tmmhnf.a_washer_dryer_owned,
         tmmhnf.a_washer_dryer_use,
         tmmhnf.a_washing_machine_age,
         tmmhnf.a_washing_machine_owned,
         tmmhnf.a_washing_machine_use,
         tmmhnf.ka_electric_hob_age,
         tmmhnf.ka_electric_hob_owned,
         tmmhnf.ka_electric_hob_use,
         tmmhnf.ka_electric_oven_age,
         tmmhnf.ka_electric_oven_owned,
         tmmhnf.ka_electric_oven_use,
         tmmhnf.ka_fridge_freezer_age,
         tmmhnf.ka_fridge_freezer_owned,
         tmmhnf.ka_fridge_freezer_use,
         tmmhnf.ka_gas_hob_age,
         tmmhnf.ka_gas_hob_owned,
         tmmhnf.ka_gas_hob_use,
         tmmhnf.ka_gas_oven_age,
         tmmhnf.ka_gas_oven_owned,
         tmmhnf.ka_gas_oven_use,
         tmmhnf.ka_standalone_freezer_age,
         tmmhnf.ka_standalone_freezer_owned,
         tmmhnf.ka_standalone_freezer_use,
         tmmhnf.ka_standalone_fridge_age,
         tmmhnf.ka_standalone_fridge_owned,
         tmmhnf.ka_standalone_fridge_use,
         tmmhnf.person_10_age,
         tmmhnf.person_11_age,
         tmmhnf.person_12_age,
         tmmhnf.person_13_age,
         tmmhnf.person_14_age,
         tmmhnf.person_15_age,
         tmmhnf.person_16_age,
         tmmhnf.person_17_age,
         tmmhnf.person_18_age,
         tmmhnf.person_19_age,
         tmmhnf.person_1_age,
         tmmhnf.person_20_age,
         tmmhnf.person_21_age,
         tmmhnf.person_22_age,
         tmmhnf.person_23_age,
         tmmhnf.person_24_age,
         tmmhnf.person_2_age,
         tmmhnf.person_3_age,
         tmmhnf.person_4_age,
         tmmhnf.person_5_age,
         tmmhnf.person_6_age,
         tmmhnf.person_7_age,
         tmmhnf.person_8_age,
         tmmhnf.person_9_age
order by su.external_id)

create table temp_ucl_extract_2019_05_08 as
select su.external_id           as account_id,
       rcup.user_id             as igloo_user_id,
       reg.id                   as registration_id,
       rca.uprn                 as registration_uprn,
       ac.status                as account_status,
       vmp_elec.meterpointtype  as meterpoint_type_elec,
       vmp_gas.meterpointtype   as meterpoint_type_gas,
       case
         when (vmp_elec.meterpointtype is not null and vmp_gas.meterpointtype is not null)
                 then 'dual_fuel'
         else 'single_fuel' end as dual,
       case
         when (mp_elec.supplyenddate is null or mp_elec.supplyenddate >= current_date) then 'Live'
         else 'Not Live' end    as meterpoints_status_elec,
       case
         when (vmp_gas.meterpointtype = 'G' and
               (mp_gas.supplyenddate is null or mp_gas.supplyenddate >= current_date)) then 'Live'
         else 'Not Live' end    as meterpoints_status_gas,
       mp_elec.supplystartdate  as supply_startdate_elec,
       mp_elec.supplyenddate    as supply_enddate_elec,
       mp_gas.supplystartdate   as supply_startdate_gas,
       mp_gas.supplyenddate     as supply_enddate_gas,
       qu.num_bedrooms,
       qu.num_adults,
       qu.heating_type,
       rca.postcode             as postcode,
    --EPC
       epc.current_energy_rating,
       epc.potential_energy_rating,
       epc.current_energy_efficiency,
       epc.potential_energy_efficiency,
       epc.property_type as property_type_epc,
       epc.built_form,
       epc.inspection_date,
       epc.local_authority,
       epc.constituency,
       epc.county,
       epc.lodgement_date,
       epc.transaction_type,
       epc.environment_impact_current,
       epc.environment_impact_potential,
       epc.energy_consumption_current,
       epc.energy_consumption_potential,
       epc.co2_emissions_current,
       epc.co2_emiss_curr_per_floor_area,
       epc.co2_emissions_potential,
       epc.lighting_cost_current,
       epc.lighting_cost_potential,
       epc.heating_cost_current,
       epc.heating_cost_potential,
       epc.hot_water_cost_current,
       epc.hot_water_cost_potential,
       epc.total_floor_area,
       epc.energy_tariff,
       epc.mains_gas_flag,
       epc.floor_level,
       epc.flat_top_storey,
       epc.flat_storey_count,
       epc.main_heating_controls,
       epc.multi_glaze_proportion,
       epc.glazed_type,
       epc.glazed_area,
       epc.extension_count,
       epc.number_habitable_rooms,
       epc.number_heated_rooms,
       epc.low_energy_lighting,
       epc.number_open_fireplaces,
       epc.hotwater_description,
       epc.hot_water_energy_eff,
       epc.hot_water_env_eff,
       epc.floor_description,
       epc.floor_energy_eff,
       epc.floor_env_eff,
       epc.windows_description,
       epc.windows_energy_eff,
       epc.windows_env_eff,
       epc.walls_description,
       epc.walls_energy_eff,
       epc.walls_env_eff,
       epc.secondheat_description,
       epc.sheating_energy_eff,
       epc.sheating_env_eff,
       epc.roof_description,
       epc.roof_energy_eff,
       epc.roof_env_eff,
       epc.mainheat_description,
       epc.mainheat_energy_eff,
       epc.mainheat_env_eff,
       epc.mainheatcont_description,
       epc.mainheatc_energy_eff,
       epc.mainheatc_env_eff,
       epc.lighting_description,
       epc.lighting_energy_eff,
       epc.lighting_env_eff,
       epc.main_fuel,
       epc.wind_turbine_count,
       epc.heat_loss_corridoor,
       epc.unheated_corridor_length,
       epc.floor_height,
       epc.photo_supply,
       epc.solar_water_heating_flag,
       epc.mechanical_ventilation,
    -- Epc Recommendations
       sepr.improvement_descr_text,
       sepr.improvement_id,
       sepr.improvement_id_text,
       sepr.improvement_item,
       sepr.improvement_summary_text,
    --Land Registry
       rlr.transaction_date,
       rlr.new_build,
       rlr.price_paid,
       rlr.property_type as property_type_land_registry,
       rlr.record_status,
       rlr.transaction_category,
    -- ref_calculate_eac_aq
       rce.register_id          as register_id_eac,
       rce.industry_eac         as register_industry_eac,
       rce.igloo_eac            as register_annualised_eac,
       rcg.register_id          as register_id_aq,
       rcg.industry_aq          as register_industry_aq,
       rcg.igloo_aq             as register_annualised_aq,
    --Non-Fixed MMH
       tmmhnf.user_id,
       tmmhnf.dhw_tank_present,
       tmmhnf.heating_control,
       tmmhnf.heating_extent,
       tmmhnf.number_of_bedrooms,
       tmmhnf.number_of_occupants,
       tmmhnf.heating_age,
       tmmhnf.dwelling_age,
       tmmhnf.heating_setpoint,
       tmmhnf.main_heat_source,
       tmmhnf.dwelling_type,
       tmmhnf.a_dishwasher_age,
       tmmhnf.a_dishwasher_owned,
       tmmhnf.a_dishwasher_use,
       tmmhnf.a_power_shower_age,
       tmmhnf.a_power_shower_owned,
       tmmhnf.a_power_shower_use,
       tmmhnf.a_tumble_dryer_age,
       tmmhnf.a_tumble_dryer_owned,
       tmmhnf.a_tumble_dryer_use,
       tmmhnf.a_washer_dryer_age,
       tmmhnf.a_washer_dryer_owned,
       tmmhnf.a_washer_dryer_use,
       tmmhnf.a_washing_machine_age,
       tmmhnf.a_washing_machine_owned,
       tmmhnf.a_washing_machine_use,
       tmmhnf.ka_electric_hob_age,
       tmmhnf.ka_electric_hob_owned,
       tmmhnf.ka_electric_hob_use,
       tmmhnf.ka_electric_oven_age,
       tmmhnf.ka_electric_oven_owned,
       tmmhnf.ka_electric_oven_use,
       tmmhnf.ka_fridge_freezer_age,
       tmmhnf.ka_fridge_freezer_owned,
       tmmhnf.ka_fridge_freezer_use,
       tmmhnf.ka_gas_hob_age,
       tmmhnf.ka_gas_hob_owned,
       tmmhnf.ka_gas_hob_use,
       tmmhnf.ka_gas_oven_age,
       tmmhnf.ka_gas_oven_owned,
       tmmhnf.ka_gas_oven_use,
       tmmhnf.ka_standalone_freezer_age,
       tmmhnf.ka_standalone_freezer_owned,
       tmmhnf.ka_standalone_freezer_use,
       tmmhnf.ka_standalone_fridge_age,
       tmmhnf.ka_standalone_fridge_owned,
       tmmhnf.ka_standalone_fridge_use,
       tmmhnf.person_10_age,
       tmmhnf.person_11_age,
       tmmhnf.person_12_age,
       tmmhnf.person_13_age,
       tmmhnf.person_14_age,
       tmmhnf.person_15_age,
       tmmhnf.person_16_age,
       tmmhnf.person_17_age,
       tmmhnf.person_18_age,
       tmmhnf.person_19_age,
       tmmhnf.person_1_age,
       tmmhnf.person_20_age,
       tmmhnf.person_21_age,
       tmmhnf.person_22_age,
       tmmhnf.person_23_age,
       tmmhnf.person_24_age,
       tmmhnf.person_2_age,
       tmmhnf.person_3_age,
       tmmhnf.person_4_age,
       tmmhnf.person_5_age,
       tmmhnf.person_6_age,
       tmmhnf.person_7_age,
       tmmhnf.person_8_age,
       tmmhnf.person_9_age

from ref_cdb_supply_contracts su
       inner join ref_cdb_user_permissions rcup on su.id = rcup.permissionable_id and permission_level = 0 and
                                                   permissionable_type = 'App\\SupplyContract'
       inner join ref_cdb_users rcu on rcup.user_id = rcu.id
       left outer join ref_account_status ac on ac.account_id = su.external_id
       left outer join vw_meterpoint_status_elec vmp_elec on vmp_elec.account_id = su.external_id
       left outer join vw_meterpoint_status_gas vmp_gas on vmp_gas.account_id = su.external_id
       left outer join ref_meterpoints mp_elec
         on mp_elec.account_id = vmp_elec.account_id and mp_elec.meterpointtype = 'E' and
            (mp_elec.supplyenddate < getdate() or mp_elec.supplyenddate is null)
       left outer join ref_meterpoints_attributes rma_gsp
         on mp_elec.meter_point_id = rma_gsp.meter_point_id and rma_gsp.attributes_attributename = 'GSP'
       left outer join ref_meterpoints mp_gas on mp_gas.account_id = vmp_gas.account_id and mp_gas.meterpointtype = 'G'
       left outer join ref_meterpoints_attributes rma_ldz
         on mp_gas.meter_point_id = rma_ldz.meter_point_id and rma_ldz.attributes_attributename = 'LDZ'
       left outer join ref_cdb_addresses rca on su.supply_address_id = rca.id
       left outer join ref_epc_certificates epc on rca.postcode = REPLACE(epc.postcode, ' ', '') and
                                                   public.epcaddressmapping(sub_building_name_number,
                                                                            building_name_number, thoroughfare,
                                                                            dependent_locality) =
                                                   trim(lower(replace(replace(epc.address, '- ', ' '), '-', ' ')))
       left outer join aws_s3_stage2_extracts.stage2_epcrecommendations sepr on epc.lmk_key = sepr.lmk_key
       left outer join ref_land_registry rlr on rca.id = rlr.id
       left outer join ref_cdb_registrations reg on su.registration_id = reg.id
       left outer join ref_cdb_quotes qu on reg.quote_id = qu.id
       left outer join ref_calculated_eac rce on su.external_id = rce.account_id
       left outer join ref_calculated_aq rcg on su.external_id = rcg.account_id
     --  left outer join temp_me_and_my_home_fixed tmmhf on rcup.user_id = tmmhf.user_id
       left outer join aws_s3_stage2_extracts.temp_mmh_non_fixed_answers tmmhnf on rcup.user_id = tmmhnf.user_id
where su.external_id is not null
  and ac.status = 'Live'
group by su.external_id,
         rcup.user_id,
         reg.id,
         rca.uprn,
         ac.status,
         vmp_elec.meterpointtype,
         vmp_gas.meterpointtype,
         case
           when (vmp_elec.meterpointtype is not null and vmp_gas.meterpointtype is not null)
                   then 'dual_fuel'
           else 'single_fuel' end,
         case
           when (mp_elec.supplyenddate is null or mp_elec.supplyenddate >= current_date) then 'Live'
           else 'Not Live' end,
         case
           when (vmp_gas.meterpointtype = 'G' and
                 (mp_gas.supplyenddate is null or mp_gas.supplyenddate >= current_date)) then 'Live'
           else 'Not Live' end,
         mp_elec.supplystartdate,
         mp_elec.supplyenddate,
         mp_gas.supplystartdate,
         mp_gas.supplyenddate,
--Quotes Extract
         qu.num_bedrooms,
         qu.num_adults,
         qu.heating_type,
         rca.postcode,
--EPC Certificates
         epc.current_energy_rating,
         epc.potential_energy_rating,
         epc.current_energy_efficiency,
         epc.potential_energy_efficiency,
         epc.property_type,
         epc.built_form,
         epc.inspection_date,
         epc.local_authority,
         epc.constituency,
         epc.county,
         epc.lodgement_date,
         epc.transaction_type,
         epc.environment_impact_current,
         epc.environment_impact_potential,
         epc.energy_consumption_current,
         epc.energy_consumption_potential,
         epc.co2_emissions_current,
         epc.co2_emiss_curr_per_floor_area,
         epc.co2_emissions_potential,
         epc.lighting_cost_current,
         epc.lighting_cost_potential,
         epc.heating_cost_current,
         epc.heating_cost_potential,
         epc.hot_water_cost_current,
         epc.hot_water_cost_potential,
         epc.total_floor_area,
         epc.energy_tariff,
         epc.mains_gas_flag,
         epc.floor_level,
         epc.flat_top_storey,
         epc.flat_storey_count,
         epc.main_heating_controls,
         epc.multi_glaze_proportion,
         epc.glazed_type,
         epc.glazed_area,
         epc.extension_count,
         epc.number_habitable_rooms,
         epc.number_heated_rooms,
         epc.low_energy_lighting,
         epc.number_open_fireplaces,
         epc.hotwater_description,
         epc.hot_water_energy_eff,
         epc.hot_water_env_eff,
         epc.floor_description,
         epc.floor_energy_eff,
         epc.floor_env_eff,
         epc.windows_description,
         epc.windows_energy_eff,
         epc.windows_env_eff,
         epc.walls_description,
         epc.walls_energy_eff,
         epc.walls_env_eff,
         epc.secondheat_description,
         epc.sheating_energy_eff,
         epc.sheating_env_eff,
         epc.roof_description,
         epc.roof_energy_eff,
         epc.roof_env_eff,
         epc.mainheat_description,
         epc.mainheat_energy_eff,
         epc.mainheat_env_eff,
         epc.mainheatcont_description,
         epc.mainheatc_energy_eff,
         epc.mainheatc_env_eff,
         epc.lighting_description,
         epc.lighting_energy_eff,
         epc.lighting_env_eff,
         epc.main_fuel,
         epc.wind_turbine_count,
         epc.heat_loss_corridoor,
         epc.unheated_corridor_length,
         epc.floor_height,
         epc.photo_supply,
         epc.solar_water_heating_flag,
         epc.mechanical_ventilation,
-- Epc Recommendations
         sepr.improvement_descr_text,
         sepr.improvement_id,
         sepr.improvement_id_text,
         sepr.improvement_item,
         sepr.improvement_summary_text,
--Land Registry
         rlr.transaction_date,
         rlr.new_build,
         rlr.price_paid,
         rlr.property_type,
         rlr.record_status,
         rlr.transaction_category,
-- ref_calculate_eac_aq
         rce.register_id,
         rce.industry_eac,
         rce.igloo_eac,
         rcg.register_id,
         rcg.industry_aq,
         rcg.igloo_aq,
    --Non-Fixed MMH
         tmmhnf.user_id,
         tmmhnf.dhw_tank_present,
         tmmhnf.heating_control,
         tmmhnf.heating_extent,
         tmmhnf.number_of_bedrooms,
         tmmhnf.number_of_occupants,
         tmmhnf.heating_age,
         tmmhnf.dwelling_age,
         tmmhnf.heating_setpoint,
         tmmhnf.main_heat_source,
         tmmhnf.dwelling_type,
         tmmhnf.a_dishwasher_age,
         tmmhnf.a_dishwasher_owned,
         tmmhnf.a_dishwasher_use,
         tmmhnf.a_power_shower_age,
         tmmhnf.a_power_shower_owned,
         tmmhnf.a_power_shower_use,
         tmmhnf.a_tumble_dryer_age,
         tmmhnf.a_tumble_dryer_owned,
         tmmhnf.a_tumble_dryer_use,
         tmmhnf.a_washer_dryer_age,
         tmmhnf.a_washer_dryer_owned,
         tmmhnf.a_washer_dryer_use,
         tmmhnf.a_washing_machine_age,
         tmmhnf.a_washing_machine_owned,
         tmmhnf.a_washing_machine_use,
         tmmhnf.ka_electric_hob_age,
         tmmhnf.ka_electric_hob_owned,
         tmmhnf.ka_electric_hob_use,
         tmmhnf.ka_electric_oven_age,
         tmmhnf.ka_electric_oven_owned,
         tmmhnf.ka_electric_oven_use,
         tmmhnf.ka_fridge_freezer_age,
         tmmhnf.ka_fridge_freezer_owned,
         tmmhnf.ka_fridge_freezer_use,
         tmmhnf.ka_gas_hob_age,
         tmmhnf.ka_gas_hob_owned,
         tmmhnf.ka_gas_hob_use,
         tmmhnf.ka_gas_oven_age,
         tmmhnf.ka_gas_oven_owned,
         tmmhnf.ka_gas_oven_use,
         tmmhnf.ka_standalone_freezer_age,
         tmmhnf.ka_standalone_freezer_owned,
         tmmhnf.ka_standalone_freezer_use,
         tmmhnf.ka_standalone_fridge_age,
         tmmhnf.ka_standalone_fridge_owned,
         tmmhnf.ka_standalone_fridge_use,
         tmmhnf.person_10_age,
         tmmhnf.person_11_age,
         tmmhnf.person_12_age,
         tmmhnf.person_13_age,
         tmmhnf.person_14_age,
         tmmhnf.person_15_age,
         tmmhnf.person_16_age,
         tmmhnf.person_17_age,
         tmmhnf.person_18_age,
         tmmhnf.person_19_age,
         tmmhnf.person_1_age,
         tmmhnf.person_20_age,
         tmmhnf.person_21_age,
         tmmhnf.person_22_age,
         tmmhnf.person_23_age,
         tmmhnf.person_24_age,
         tmmhnf.person_2_age,
         tmmhnf.person_3_age,
         tmmhnf.person_4_age,
         tmmhnf.person_5_age,
         tmmhnf.person_6_age,
         tmmhnf.person_7_age,
         tmmhnf.person_8_age,
         tmmhnf.person_9_age
order by su.external_id