select nullif(mandate_id, ''),
       nullif(customerid, ''),
       nullif(new_mandate_id, ''),
       nullif(created_at, '')::timestamp,
       nullif(next_possible_charge_date, '')::timestamp,
       payments_require_approval = 'True'       as payments_require_approval,
       nullif(reference, ''),
       nullif(scheme, ''),
       nullif(status, ''),
       nullif(creditor, ''),
       nullif(customer_bank_account, ''),
       nullif(ensekid, '')::bigint,
       nullif(ensekstatementid, '')::bigint,
       nullif(extract_timestamp, '')::timestamp as last_updated_igloo,
       getdate()                                as etlchange
from aws_fin_stage1_extracts.fin_stage2_gocardlessmandates