select nullif(mandate_id,'')::text,
       nullif(customerid,'')::text,
       nullif(new_mandate_id,'')::text,
       nullif(created_at,'')::timestamp,
       nullif(next_possible_charge_date,'')::timestamp,
       payments_require_approval::boolean,
       nullif(reference,'')::text,
       nullif(scheme,'')::text,
       nullif(status,'')::text,
       nullif(creditor,'')::text,
       nullif(customer_bank_account,'')::text,
       nullif(ensekid,'')::bigint,
       nullif(ensekstatementid,'')::bigint,
       nullif(extract_timestamp,'')::timestamp as last_updated_igloo,
       getdate()                    as etlchange
from aws_fin_stage1_extracts.fin_stage2_gocardlessmandates