SELECT nullif(id, ''),
       nullif(created_at, '')::timestamp,
       nullif(amount, '')::bigint,
       nullif(currency, ''),
       nullif(status, ''),
       nullif(name, ''),
       nullif(start_date, '')::timestamp,
       nullif(end_date, '')::timestamp,
       nullif("interval", '')::bigint,
       nullif(interval_unit, ''),
       nullif(day_of_month, '')::bigint         as day_of_month,
       nullif(month, '')::int,
       nullif(count_no, '')::bigint,
       nullif(payment_reference, ''),
       nullif(app_fee, '')::bigint              as app_fee,
       retry_if_possible = 'true'               as retry_if_possible,
       nullif(mandate, ''),
       nullif(charge_date, '')::timestamp,
       nullif(amount_subscription, '')::bigint,
       nullif(extract_timestamp, '')::timestamp as last_updated_igloo,
       getdate()                                as etlchange
FROM aws_fin_stage1_extracts.fin_stage2_gocardlesssubscriptions