select nullif(id, '')::text,
       amount::bigint,
       amount_refunded::bigint,
       nullif(charge_date, '')::timestamp,
       nullif(created_at, '')::timestamp,
       nullif(currency, '')::text,
       nullif(description, '')::text,
       nullif(reference, '')::text,
       nullif(status, '')::text,
       nullif(payout, '')::text,
       nullif(mandate, '')::text,
       nullif(subscription, '')::text,
       ensekid::bigint,
       statementid::bigint,
       nullif(extract_timestamp, '')::timestamp as last_updated_igloo,
       getdate()                                as etlchange
from aws_fin_stage1_extracts.fin_stage2_gocardlesspayments