select nullif(id, ''),
       nullif(amount, '')::bigint,
       nullif(amount_refunded, '')::bigint,
       nullif(charge_date, '')::timestamp,
       nullif(created_at, '')::timestamp,
       nullif(currency, ''),
       nullif(description, ''),
       nullif(reference, ''),
       nullif(status, ''),
       nullif(payout, ''),
       nullif(mandate, ''),
       nullif(subscription, ''),
       nullif(ensekid, '')::bigint,
       nullif(statementid, '')::bigint,
       nullif(extract_timestamp, '')::timestamp as last_updated_igloo,
       getdate()                                as etlchange
from aws_fin_stage1_extracts.fin_stage2_gocardlesspayments