SELECT nullif(id, '')::text,
       nullif(created_at, '')::timestamp,
       amount::bigint,
       nullif(currency, '')::text,
       nullif(status, '')::text,
       nullif(name, '')::text,
       nullif(start_date, '')::timestamp,
       nullif(end_date, '')::timestamp,
       "interval"::bigint,
       nullif(interval_unit, '')::text,
       day_of_month::bigint as day_of_month,
       nullif(month, '')::int,
       count_no::bigint,
       nullif(payment_reference, '')::text,
       app_fee::bigint      as app_fee,
       retry_if_possible::boolean              as retry_if_possible,
       nullif(mandate, '')::text,
       nullif(charge_date, '')::timestamp,
       amount_subscription::bigint,
       nullif(extract_timestamp, '')::timestamp            as last_updated_igloo,
       getdate()                                           as etlchange
FROM aws_fin_stage1_extracts.fin_stage2_gocardlesssubscriptions