create table temp_elec_attributes_daily_and_hourly_calculated_reads
  as
select su.external_id                                       as account_id,
       rcup.user_id                                         as igloo_user_id,
       rca.postcode                                         as supply_postcode,
       ac.status                                            as account_status,
       mp_elec.meterpointtype                               as meterpoint_type_elec,
       case
         when (mp_elec.supplyenddate is null or mp_elec.supplyenddate >= current_date) then 'Live'
         else 'Not Live' end                                as meterpoints_status_elec,
       rse.status                                           as registration_status_elec,
       mp_elec.supplystartdate                              as supply_startdate_elec,
       mp_elec.supplyenddate                                as supply_enddate_elec,
       su.created_at                                        as supply_contract_creation_date,
       mp_elec.meter_point_id                               as meter_point_id_elec,
       mt_elec.meter_id                                     as meter_id_elec,
       reg_elec.register_id                                 as register_id_elec,
       reg_elec.registers_eacaq                             as register_elec_eacaq,
       reg_elec.registers_registerreference                 as register_elec_reference,
       reg_elec.registers_tpr                               as register_elec_tpr,
         elecread.read_min_created_date_elec,
         elecread.read_max_created_date_elec,
         elecread.read_min_readings_elec,
         elecread.read_max_readings_elec,
         elecread.read_months_diff_elec,
         elecread.read_days_diff_elec,
         elecread.read_consumption_elec,
         elecread.industry_eac,
         elecread.tpr,
         elecread.d18_st_date,
         elecread.ppc_sum,
         elecread.igloo_eac,
         elecread.igloo_edc,
         elecread.igloo_edhc_1,
         elecread.igloo_edhc_2,
         elecread.igloo_edhc_3,
         elecread.igloo_edhc_4,
         elecread.igloo_edhc_5,
         elecread.igloo_edhc_6,
         elecread.igloo_edhc_7,
         elecread.igloo_edhc_8,
         elecread.igloo_edhc_9,
         elecread.igloo_edhc_10,
         elecread.igloo_edhc_11,
         elecread.igloo_edhc_12,
         elecread.igloo_edhc_13,
         elecread.igloo_edhc_14,
         elecread.igloo_edhc_15,
         elecread.igloo_edhc_16,
         elecread.igloo_edhc_17,
         elecread.igloo_edhc_18,
         elecread.igloo_edhc_19,
         elecread.igloo_edhc_20,
         elecread.igloo_edhc_21,
         elecread.igloo_edhc_22,
         elecread.igloo_edhc_23,
         elecread.igloo_edhc_24,
         elecread.igloo_edhc_25,
         elecread.igloo_edhc_26,
         elecread.igloo_edhc_27,
        elecread.igloo_edhc_28,
         elecread.igloo_edhc_29,
         elecread.igloo_edhc_30,
         elecread.igloo_edhc_31,
         elecread.igloo_edhc_32,
         elecread.igloo_edhc_33,
         elecread.igloo_edhc_34,
         elecread.igloo_edhc_35,
         elecread.igloo_edhc_36,
         elecread.igloo_edhc_37,
         elecread.igloo_edhc_38,
         elecread.igloo_edhc_39,
         elecread.igloo_edhc_40,
         elecread.igloo_edhc_41,
         elecread.igloo_edhc_42,
         elecread.igloo_edhc_43,
         elecread.igloo_edhc_44,
         elecread.igloo_edhc_45,
         elecread.igloo_edhc_46,
         elecread.igloo_edhc_47,
         elecread.igloo_edhc_48
from ref_cdb_supply_contracts su --inner join temp_cab_dates_quarter4_2018 we on we.external_id = su.external_id
       inner join ref_cdb_user_permissions rcup on su.id = rcup.permissionable_id and permission_level = 0 and
                                                   permissionable_type = 'App\\SupplyContract'
       inner join ref_cdb_users rcu on rcup.user_id = rcu.id
       inner join ref_cdb_addresses rca on su.supply_address_id = rca.id
       inner join ref_account_status ac on ac.account_id = su.external_id
       inner join ref_meterpoints mp_elec on mp_elec.account_id = su.external_id and mp_elec.meterpointtype = 'E'
       inner join ref_meterpoints_attributes mpa_elec on mp_elec.meter_point_id = mpa_elec.meter_point_id and
                                                              attributes_effectivetodate is null
       inner join ref_meters mt_elec
         on mp_elec.meter_point_id = mt_elec.meter_point_id and mt_elec.removeddate is null
       inner join ref_registers reg_elec on mt_elec.meter_id = reg_elec.meter_id
       inner join ref_registrations_status_elec rse on mp_elec.account_id = rse.account_id
       inner join temp_igloo_daily_and_hourly_calculated_reads elecread on su.external_id = elecread.account_id and mp_elec.meter_point_id = elecread.meterpoint_id and reg_elec.register_id =elecread.register_id
    --     where su.external_id = 11993
group by su.external_id,
         rcup.user_id,
         rca.postcode,
         ac.status,
         mp_elec.meterpointtype,
         case
           when (mp_elec.meterpointtype = 'E' and (mp_elec.supplyenddate is null or
                                                   (mp_elec.supplyenddate >= current_date and
                                                    mp_elec.supplyenddate >= mp_elec.supplystartdate))) then 'Live'
           else 'Not Live' end,
         rse.status,
         mp_elec.supplystartdate,
         mp_elec.supplyenddate,
         su.created_at,
         mp_elec.meter_point_id,
         mt_elec.meter_id,
         reg_elec.register_id,
         reg_elec.registers_eacaq,
         reg_elec.registers_registerreference,
         reg_elec.registers_tpr,
           elecread.read_min_created_date_elec,
         elecread.read_max_created_date_elec,
         elecread.read_min_readings_elec,
         elecread.read_max_readings_elec,
         elecread.read_months_diff_elec,
         elecread.read_days_diff_elec,
         elecread.read_consumption_elec,
         elecread.industry_eac,
         elecread.tpr,
         elecread.d18_st_date,
         elecread.ppc_sum,
         elecread.igloo_eac,
         elecread.igloo_edc,
         elecread.igloo_edhc_1,
         elecread.igloo_edhc_2,
         elecread.igloo_edhc_3,
         elecread.igloo_edhc_4,
         elecread.igloo_edhc_5,
         elecread.igloo_edhc_6,
         elecread.igloo_edhc_7,
         elecread.igloo_edhc_8,
         elecread.igloo_edhc_9,
         elecread.igloo_edhc_10,
         elecread.igloo_edhc_11,
         elecread.igloo_edhc_12,
         elecread.igloo_edhc_13,
         elecread.igloo_edhc_14,
         elecread.igloo_edhc_15,
         elecread.igloo_edhc_16,
         elecread.igloo_edhc_17,
         elecread.igloo_edhc_18,
         elecread.igloo_edhc_19,
         elecread.igloo_edhc_20,
         elecread.igloo_edhc_21,
         elecread.igloo_edhc_22,
         elecread.igloo_edhc_23,
         elecread.igloo_edhc_24,
         elecread.igloo_edhc_25,
         elecread.igloo_edhc_26,
         elecread.igloo_edhc_27,
        elecread.igloo_edhc_28,
         elecread.igloo_edhc_29,
         elecread.igloo_edhc_30,
         elecread.igloo_edhc_31,
         elecread.igloo_edhc_32,
         elecread.igloo_edhc_33,
         elecread.igloo_edhc_34,
         elecread.igloo_edhc_35,
         elecread.igloo_edhc_36,
         elecread.igloo_edhc_37,
         elecread.igloo_edhc_38,
         elecread.igloo_edhc_39,
         elecread.igloo_edhc_40,
         elecread.igloo_edhc_41,
         elecread.igloo_edhc_42,
         elecread.igloo_edhc_43,
         elecread.igloo_edhc_44,
         elecread.igloo_edhc_45,
         elecread.igloo_edhc_46,
         elecread.igloo_edhc_47,
         elecread.igloo_edhc_48
    --MeterPoints Attributes Elec
order by su.external_id
