

select
	dspinventory_cad_cplstatus ::varchar(15),
	dspinventory_cad_cspregion ::varchar(15),
	dspinventory_cad_datecommissioned ::timestamp ,
	dspinventory_cad_devicefirmwareversion ::varchar(15),
	dspinventory_cad_devicefirmwareversionstatus ::varchar(15),
	dspinventory_cad_devicegbcsversion ::varchar(15),
	dspinventory_cad_deviceid ::varchar(100),
	dspinventory_cad_devicemanufacturer ::varchar(15),
	dspinventory_cad_devicemodel ::varchar(15),
	dspinventory_cad_devicestatus ::varchar(15),
	dspinventory_cad_devicetype ::varchar(15),
	dspinventory_cad_esmevariant ::varchar(15),
	dspinventory_cad_exportmpan ::bigint ,
	dspinventory_cad_hanvariant ::varchar(15),
	dspinventory_cad_importmpxn ::bigint ,
	dspinventory_cad_propertyfilter_addressidentifier ::varchar(100),
	dspinventory_cad_propertyfilter_postcode ::varchar(15),
	dspinventory_cad_s1sp ::varchar(15),
	dspinventory_cad_smetschtsversion ::varchar(15),
	dspinventory_cad_secondaryimportmpan ::bigint ,
	dspinventory_cad_uprn ::varchar(15),
	dspinventory_chf_cplstatus ::varchar(15),
	dspinventory_chf_cspregion ::varchar(15),
	dspinventory_chf_datecommissioned ::timestamp ,
	dspinventory_chf_devicefirmwareversion ::varchar(15),
	dspinventory_chf_devicefirmwareversionstatus ::varchar(15),
	dspinventory_chf_devicegbcsversion ::varchar(15),
	dspinventory_chf_deviceid ::varchar(100),
	dspinventory_chf_devicemanufacturer ::varchar(15),
	dspinventory_chf_devicemodel ::varchar(15),
	dspinventory_chf_devicestatus ::varchar(50),
	dspinventory_chf_devicetype ::varchar(15),
	dspinventory_chf_esmevariant ::varchar(15),
	dspinventory_chf_exportmpan ::bigint ,
	dspinventory_chf_hanvariant ::varchar(15),
	dspinventory_chf_importmpxn ::bigint ,
	dspinventory_chf_propertyfilter_addressidentifier ::varchar(100),
	dspinventory_chf_propertyfilter_postcode ::varchar(15),
	dspinventory_chf_s1sp ::varchar(15),
	dspinventory_chf_smetschtsversion ::varchar(15),
	dspinventory_chf_secondaryimportmpan ::bigint ,
	dspinventory_chf_uprn ::bigint ,
	dspinventory_esme_cplstatus ::varchar(15),
	dspinventory_esme_cspregion ::varchar(15),
	dspinventory_esme_datecommissioned ::timestamp ,
	dspinventory_esme_devicefirmwareversion ::varchar(15),
	dspinventory_esme_devicefirmwareversionstatus ::varchar(15),
	dspinventory_esme_devicegbcsversion ::varchar(15),
	dspinventory_esme_deviceid ::varchar(100),
	dspinventory_esme_devicemanufacturer ::varchar(15),
	dspinventory_esme_devicemodel ::varchar(15),
	dspinventory_esme_devicestatus ::varchar(50),
	dspinventory_esme_devicetype ::varchar(15),
	dspinventory_esme_esmevariant ::varchar(15),
	dspinventory_esme_exportmpan ::bigint ,
	dspinventory_esme_hanvariant ::varchar(15),
	dspinventory_esme_importmpxn ::bigint ,
	dspinventory_esme_propertyfilter_addressidentifier ::varchar(100),
	dspinventory_esme_propertyfilter_postcode ::varchar(15),
	dspinventory_esme_s1sp ::varchar(15),
	dspinventory_esme_smetschtsversion ::varchar(15),
	dspinventory_esme_secondaryimportmpan ::bigint ,
	dspinventory_esme_uprn ::bigint ,
	dspinventory_gpf_cplstatus ::varchar(15),
	dspinventory_gpf_cspregion ::varchar(15),
	dspinventory_gpf_datecommissioned ::timestamp ,
	dspinventory_gpf_devicefirmwareversion ::varchar(15),
	dspinventory_gpf_devicefirmwareversionstatus ::varchar(15),
	dspinventory_gpf_devicegbcsversion ::varchar(15),
	dspinventory_gpf_deviceid ::varchar(100),
	dspinventory_gpf_devicemanufacturer ::varchar(15),
	dspinventory_gpf_devicemodel ::varchar(15),
	dspinventory_gpf_devicestatus ::varchar(50),
	dspinventory_gpf_devicetype ::varchar(15),
	dspinventory_gpf_esmevariant ::varchar(15),
	dspinventory_gpf_exportmpan ::bigint ,
	dspinventory_gpf_hanvariant ::varchar(15),
	dspinventory_gpf_importmpxn ::bigint ,
	dspinventory_gpf_propertyfilter_addressidentifier ::varchar(100),
	dspinventory_gpf_propertyfilter_postcode ::varchar(15),
	dspinventory_gpf_s1sp ::varchar(15),
	dspinventory_gpf_smetschtsversion ::varchar(15) ,
	dspinventory_gpf_secondaryimportmpan ::bigint ,
	dspinventory_gpf_uprn ::bigint ,
	dspinventory_gsme_cplstatus ::varchar(15),
	dspinventory_gsme_cspregion ::varchar(15),
	dspinventory_gsme_datecommissioned ::timestamp ,
	dspinventory_gsme_devicefirmwareversion ::varchar(15),
	dspinventory_gsme_devicefirmwareversionstatus ::varchar(15),
	dspinventory_gsme_devicegbcsversion ::varchar(15),
	dspinventory_gsme_deviceid ::varchar(100),
	dspinventory_gsme_devicemanufacturer ::varchar(15),
	dspinventory_gsme_devicemodel ::varchar(15),
	dspinventory_gsme_devicestatus ::varchar(50),
	dspinventory_gsme_devicetype ::varchar(15),
	dspinventory_gsme_esmevariant ::varchar(15),
	dspinventory_gsme_exportmpan ::bigint ,
	dspinventory_gsme_hanvariant ::varchar(15),
	dspinventory_gsme_importmpxn ::bigint ,
	dspinventory_gsme_propertyfilter_addressidentifier ::varchar(100),
	dspinventory_gsme_propertyfilter_postcode ::varchar(15),
	dspinventory_gsme_s1sp ::varchar(15),
	dspinventory_gsme_smetschtsversion ::varchar(15),
	dspinventory_gsme_secondaryimportmpan ::bigint ,
	dspinventory_gsme_uprn ::bigint ,
	dspinventory_ihd_cplstatus ::varchar(15),
	dspinventory_ihd_cspregion ::varchar(15),
	dspinventory_ihd_datecommissioned ::timestamp ,
	dspinventory_ihd_devicefirmwareversion ::varchar(15),
	dspinventory_ihd_devicefirmwareversionstatus ::varchar(15),
	dspinventory_ihd_devicegbcsversion ::varchar(15),
	dspinventory_ihd_deviceid ::varchar(100),
	dspinventory_ihd_devicemanufacturer ::varchar(15),
	dspinventory_ihd_devicemodel ::varchar(15),
	dspinventory_ihd_devicestatus ::varchar(50),
	dspinventory_ihd_devicetype ::varchar(15),
	dspinventory_ihd_esmevariant ::varchar(15),
	dspinventory_ihd_exportmpan ::bigint ,
	dspinventory_ihd_hanvariant ::varchar(15),
	dspinventory_ihd_importmpxn ::bigint ,
	dspinventory_ihd_propertyfilter_addressidentifier ::varchar(100),
	dspinventory_ihd_propertyfilter_postcode ::varchar(15),
	dspinventory_ihd_s1sp ::varchar(15),
	dspinventory_ihd_smetschtsversion ::varchar(15),
	dspinventory_ihd_secondaryimportmpan ::bigint ,
	dspinventory_ihd_uprn ::bigint ,
	dspinventory_ppmid_cplstatus ::varchar(15),
	dspinventory_ppmid_cspregion ::varchar(15),
	dspinventory_ppmid_datecommissioned ::timestamp ,
	dspinventory_ppmid_devicefirmwareversion ::varchar(15),
	dspinventory_ppmid_devicefirmwareversionstatus ::varchar(15),
	dspinventory_ppmid_devicegbcsversion ::varchar(15),
	dspinventory_ppmid_deviceid ::varchar(100),
	dspinventory_ppmid_devicemanufacturer ::varchar(15),
	dspinventory_ppmid_devicemodel ::varchar(15),
	dspinventory_ppmid_devicestatus ::varchar(50),
	dspinventory_ppmid_devicetype ::varchar(15),
	dspinventory_ppmid_esmevariant ::varchar(15),
	dspinventory_ppmid_exportmpan ::bigint ,
	dspinventory_ppmid_hanvariant ::varchar(15),
	dspinventory_ppmid_importmpxn ::bigint ,
	dspinventory_ppmid_propertyfilter_addressidentifier ::varchar(100),
	dspinventory_ppmid_propertyfilter_postcode ::varchar(15),
	dspinventory_ppmid_s1sp ::varchar(15),
	dspinventory_ppmid_smetschtsversion ::varchar(15),
	dspinventory_ppmid_secondaryimportmpan ::bigint ,
	dspinventory_ppmid_uprn ::bigint ,
	deviceid ::varchar(100),
	mpxn  ::bigint ,
  etlchange::timestamp  as etlchange
from  public.ref_smart_inventory_raw

;





